### ISSUE TITLE
Unable To Map Controller

### ISSUE THREAD

**Issue by tbell999** [OpenEmu/OpenEmu#4078] opened 2020-01-01 17:21 UTC
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
2. Connected a controller such as a Dual Shock or Xbox One Wireless Controller and try to remap the auto populated the controls. 

# Expected Behavior

2. I wanted to custom map my buttons. 

# Observed Behavior

2. I Clicked on the space where the button that I wanted to map was and when I pressed the corresponding button on my controller it didn't register the command. 

# Debugging Information

- OpenEmu Version: 2.2
- macOS Version: 10.15.2

**Comment by clobber** [comment] 2020-01-01 17:30
@tbell999 Please thoroughly test this build to see if it resolves the problem:

https://send.firefox.com/download/252626e07db00654/#MQKyyqlBcBZLEXljAqH_pA

**Comment by clobber** [comment] 2020-01-04 01:23
@tbell999  Any update? Could you please test as soon as you can? I'd like to get a new release out soon with the latest input fixes.

**Comment by asyanush** [comment] 2020-01-06 20:39
@clobber Just test this version with my NES joysticks. Works perfect. Not sure if it will work with Dual Shock or Xbox One Wireless Controller, however I had the same issue with NES controllers as described early with controllers mapping.

**Comment by clobber** [comment] 2020-01-06 21:00
Thanks. I believe this is basically a duplicate of #4073 

Same general issues, fixed by the same patch.

**Closed by clobber** 2020-01-06 21:00 UTC
Labels: duplicate
