### ISSUE TITLE
OpenEmu fails to display Mednafen video output in Mojave 10.14.1 Beta 4

### ISSUE THREAD

**Issue by proggeramlug** [OpenEmu/OpenEmu#3772] opened 2018-10-21 21:43 UTC
Previously, OpenEmu was able to play Sony Playstation games via the Mednafen core without a problem. Since installing the 10.14.1 beta, it has stopped displaying any video of any kind in the game window.

# Steps to reproduce

1. Install macOS Mojave 10.14.1 beta 4 or later
1. Install OpenEmu 2.0.7
1. Run OpenEmu and ensure the Mednafen core is installed.
1. Add any Sony Playstation game to the library. My issue is appearing in particular with Chrono Cross (discs 1 and 2).
1. Start the game

# Expected Behavior

1. I expect to see the game rendering normally in the game window, as it has done in the past.

# Observed Behavior

1. The game window appears with all the expected controls (power off, restart, pause, etc.), but is otherwise blank, displaying a grey background. Audio plays normally and correctly. Based on that audio I can confirm that the game is responding correctly to input; I just can't _see_ anything. Attached is a screenshot of the game window displaying the described behavior.
1. Taking a screenshot produces a black rectangle of the appropriate size.
1. Interestingly, when stopping emulation and checking the Save States tab, the preview of the automatic save state _does_ display the correct visual state of the game at the point of the save.

# Debugging Information

- OpenEmu Version: 2.0.7 (968-gf66035e-Release)
- macOS Version: macOS Mojave 10.14.1 beta 4 (18B67a)
- Hardware: MacBookPro11,5 (mid-2015 15-inch Retina), 2.5Ghz i7 x4 cores, 16GB RAM, dual GPU (Intel Iris Pro integrated GPU, AMD Radeon R9 M370X 2GB VRAM discrete GPU)
- Game: Chrono Cross (`ccdisk.m3u`, `ccdisk1.bin`, `ccdisk1.cue`, `ccdisk2.bin`, `ccdisk2.cue`)

**Comment by clobber** [comment] 2018-10-21 21:46
Uhh report the bug to Apple, since you are supposedly "testing" macOS betas, and not us. We didn't change our code.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3768

**Closed by clobber** 2018-10-21 21:46 UTC
