### ISSUE TITLE
NES Cores

### ISSUE THREAD

**Issue by bbbradsmith** [OpenEmu/OpenEmu#3711] opened 2018-08-29 00:06 UTC
This is not really a request, just pointing out some information about active development of the NES you are using in OpenEmu.

1. There is a fork of Nestopia called Nestopia UE that has continued with active development.
https://github.com/0ldsk00l/nestopia

2. FCEUX after version 2.2.3 moved to Github:
https://github.com/TASVideos/fceux

Is the FCEU core missing the X in its name for a historical reason? I was a little confused about which core this was (thought it might actually be based on the very old FCEU). I was also surprised that the Nestopia core is the default despite appearing to be much older. (I don't have strong opinions about which core is better, but FCEUX has been a lot more accurate than it used to be since the "new PPU" option was added.)

Feel free to close / delete the "issue", I just wanted to offer that information.

**Comment by clobber** [comment] 2018-08-29 00:34
Heya Brad. Yup, we're aware of both of these. Certainly at some point I will merge in more mapper fixes from Nestopia UE. There are actually a few I merged before and others I haven't yet because they were from an infamous outside contributor and I wasn't sure if they were the "correct" fix or introduced any regressions. As for our FCEU repo, it is indeed missing the "X" for basically historical reasons. It is FCEUX version 2.2.3 as one can see from the [commit log](https://github.com/OpenEmu/FCEU-Core/commits/master) and description. Thanks for dropping by!

**Closed by clobber** 2018-08-29 00:34 UTC
