### ISSUE TITLE
Switching between "NTSC" and "SABR" produces black screen or artifacts

### ISSUE THREAD

**Issue by Feuermurmel** [OpenEmu/OpenEmu#1842] opened 2015-02-25 20:23 UTC
I'm using _OpenEmu v1.0.4_ on _OS X 10.9.5_ on a _MacBookPro10,2_ to run _EarthBound_ using the _SNES9x_ core. When I switch between the _NTSC_ and _SABR_ filters (even when selecting a different filter in-between), I consistently get either a back screen (while audio still works and the game presumably is still running) or prominent artifacts, like in the screenshot below.

The new filter is applied correctly when I close and re-open the emulator (without quitting OpenEmu) or even when I open a second emulator instance.

_Console.app_ shows the following:

	2015-02-25 9:18:41.559 PM OpenEmu[57608]: OELibraryDatabase loadFromURL: 'file:///Users/michi/Library/Application%20Support/OpenEmu/Game%20Library/'
	2015-02-25 9:18:43.011 PM WindowServer[20433]: disable_update_timeout: UI updates were forcibly disabled by application "OpenEmu" for over 1.00 seconds. Server has re-enabled them.
	2015-02-25 9:18:43.304 PM WindowServer[20433]: common_reenable_update: UI updates were finally reenabled by application "OpenEmu" after 1.49 seconds (server forcibly re-enabled them after 1.20 seconds)
	2015-02-25 9:18:43.735 PM OpenEmu[57608]: Apple Internal Keyboard / Trackpad
	2015-02-25 9:18:44.525 PM OpenEmuHelperApp[57617]: parent application is: OpenEmu
	2015-02-25 9:18:44.567 PM OpenEmuHelperApp[57617]: Some shit about the game.
	2015-02-25 9:18:44.586 PM OpenEmuHelperApp[57617]: loading /Users/michi/Library/Application Support/OpenEmu/Game Library/roms/Super Nintendo (SNES)/EarthBound (USA).sfc
	2015-02-25 9:18:44.596 PM OpenEmuHelperApp[57617]: No ROM file header found.
	2015-02-25 9:18:44.597 PM OpenEmuHelperApp[57617]: Get filename
	2015-02-25 9:18:44.606 PM OpenEmuHelperApp[57617]: "EARTH BOUND" [checksum ok] HiROM, 32Mbits, ROM+RAM+BAT, NTSC, SRAM:64Kbits, ID:MB  , CRC32:DC9BB451
	2015-02-25 9:18:44.608 PM OpenEmuHelperApp[57617]: Setting up emulation
	2015-02-25 9:18:44.639 PM OpenEmu[57608]: SETUP DONE.
	2015-02-25 9:18:45.020 PM OpenEmuHelperApp[57617]: Begin separate thread
	2015-02-25 9:18:45.025 PM OpenEmuHelperApp[57617]: Loaded (null)
	2015-02-25 9:18:45.026 PM OpenEmuHelperApp[57617]: RT policy: 0.007000s (limit 0.030000s) every 0.016639s

Nothing was printed to the console when I changed the filter.

What additional infos do you need?

![screen shot 2015-02-25 at 20 59 50](https://cloud.githubusercontent.com/assets/50332/6379606/d42b52fe-bd33-11e4-9904-8355ba675ab3.png)

**Comment by clobber** [comment] 2015-02-28 03:38
Dupe of #1659, has been fixed and will be in the next release.

**Closed by clobber** 2015-02-28 03:38 UTC
