### ISSUE TITLE
WiiMote not Pairing - M1 MacBook Pro (macOS 12 Monterey beta) 

### ISSUE THREAD

**Issue by marvinjoa** [OpenEmu/OpenEmu#4573] opened 2021-08-14 15:33 UTC
I can't get the WiiMote to pair with OpenEmu or on a system level with the Mac-Adress trick.
(It doesn't work on the Dolphin Emu either.)

Is this because of the ARM achitexture or because of the macOS beta? Did anybody run into similar issues and have a fix?

I'm on the latest version on OpenEmu

**Comment by git2358** [comment] 2021-09-06 23:35
I can confirm, I am on intel 10th gen i5 MBP with macOS 12 Monterey beta, every beta version I have tried does not allow pairing the WiiMote or Wii U Pro Controllers, I don't think it's just an M1 issue...

**Comment by emolr** [comment] 2022-01-09 22:27
Hi @marvinjoa, I'm having the same issue on macOS monterey, but I have an intel mac, so at least we san rule out that it's because of the M1 chip :/

**Comment by clobber** [comment] 2022-01-09 23:47
Same problem as #4612. Closing this in favor of that issue.

**Closed by clobber** 2022-01-09 23:47 UTC
