### ISSUE TITLE
Importing files over a network transfers the file twice

### ISSUE THREAD

**Issue by joewreschnig** [OpenEmu/OpenEmu#1135] opened 2014-02-02 22:48 UTC
Importing large files over a network drive when OpenEmu is configured to organize files takes much longer than necessary, because the importer first reads the whole file to hash it, then if it's not in the database copies it over, necessitating another full read. With smaller files this doesn't matter because stuff stays cached, but when the files are 500MB+ ISOs it'll transfer the whole file twice - which is also the time when you definitely don't want to transfer it twice.

If the files were copied into a staging area during the import before hashing, and then moved into the DB proper if they passed the hash check, this would nearly halve the time required to import them. It would make importing files that are already in the database take slightly longer but that seems like a less common case than importing files that aren't already in the library.

**Comment by cyco** [comment] 2015-02-18 22:26
Closing as dupe of #668. No need to have two issues for the same thing.

**Closed by cyco** 2015-02-18 22:26 UTC
Labels: Import, Known Bug, ⚑ Feature Request
