### ISSUE TITLE
Laggy SNES performance

### ISSUE THREAD

**Issue by Kodarta** [OpenEmu/OpenEmu#1853] opened 2015-03-04 05:14 UTC
Just trying OpenEmu for the first time. Love the layout/design/simplicity. The only problem is the SNES games are ramping in and out of "slow motion" (sorry, I'm not that technical). I'm running the SNES9x core, which, strangely, runs perfectly when run on it's own, but not through OpenEmu. I've also tried the Higan core and all the filters. No luck... Please help! OpenEmu seems like the perfect emulator otherwise. 

Specs
Macbook Pro
OSX 10.10.1
2.4 GHz Intel Core 2 Duo
4 GB 1067 MHz DDR3
NVIDIA GeForce 320M 256 MB

**Comment by mrvacbob** [comment] 2015-03-04 07:04
Please run "sudo spindump" in Terminal while you're experiencing issues, then link the resulting file here (using dropbox, gist.github.com, etc.).

**Comment by clobber** [comment] 2015-03-04 08:06
This is the client storage problem since somebody else on 320M had this.
@Kodarta We've fixed this in source already per this ticket #1762 and commit https://github.com/OpenEmu/OpenEmu/commit/52ba6f71a0aa6023dc990e97cc650a44d5cada0c. If you can build the app from source, that will fix it on your end. Otherwise, you'll have to wait until we push out the next update. No ETA.

Closing but feel free to reply back with the log, though I'm pretty sure we've fixed your issue already.

**Closed by clobber** 2015-03-04 08:06 UTC

**Comment by Kodarta** [comment] 2015-03-04 08:14
How do I go about this? "If you can build the app from source, that will fix it on your end."

**Comment by clobber** [comment] 2015-03-04 08:27
There is a guide here (https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide) that is more or less up to date, but if you're not technical then I wouldn't recommend it. Right now I don't have time to distribute a build with the fix applied or walk you through the guide though.

**Comment by Kodarta** [comment] 2015-03-04 08:29
No prob, I'll give it a shot. Thanks!

**Comment by mrvacbob** [comment] 2015-03-04 23:13
I do think the problem is fixed, but it'd be good to collect those spindump logs from different GPUs just to see what they're doing wrong.

**Comment by johnmackay13** [comment] 2015-03-05 00:46
Is there an application file someone can point me to? My XCode is failing
the build each time. I think this may solve the issue I am having, but I
cannot get it to build...

On Wed, Mar 4, 2015 at 6:13 PM, mrvacbob <notifications@github.com> wrote:

> I do think the problem is fixed, but it'd be good to collect those
> spindump logs from different GPUs just to see what they're doing wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1853#issuecomment-77271585>.
>



-- 
John N. MacKay
*Independent Arranger, Copyist, Orchestrator*
*Freelance Conductor, Brass Musician*

**Comment by Kodarta** [comment] 2015-03-05 03:47
**mrvacbob**
_I do think the problem is fixed, but it'd be good to collect those spindump logs from different GPUs just to see what they're doing wrong_

I built the app from source and now it's working great (although I'm not really sure what it's doing), so unfortunately I can't collect the logs now that' it's working... Thanks for the tips! Love the software!

So this is a video card issue related to my specific computer? I want to tell friends about OpenEmu but they won't be willing to do all the troubleshooting. 

Thanks for the help!

**Comment by mrvacbob** [comment] 2015-03-05 04:46
I wouldn't say it's their fault (might be our fault), but if you're not seeing it it's gone. Call it a workaround?

But if you'd like to go back to seeing it again, just download the last release off the website. The fix is in the apps, not the cores. And there'll be another release when it's ready…

**Comment by clobber** [comment] 2015-03-20 23:02
@Kodarta a fixed build can be downloaded here https://transfer.sh/pVz8d/openemu-1.0.4-no-clientstorage.zip

**Comment by NiGHTSaturn** [comment] 2018-01-31 17:10
I know this is an old issue, but this still goes on in the latest version on 320M cards. And since every version of SNES9X are crashing on my computer since I've updated it to 10.11.6 i'm still trying to figure it out. Also the fixed build you've posted 3 years ago is no longer available. If you need any new logs, let me know. The issue is mostly audio delay. Other than that video works fine.
