### ISSUE TITLE
Problem with my save data

### ISSUE THREAD

**Issue by luigi0301** [OpenEmu/OpenEmu#3664] opened 2018-07-04 09:16 UTC
Ok I am very new to this whole thing. I didn't know where else to look for help in this matter. So, somehow my data for a gba game is gone. it completely erased and all of my save states got pushed into trash. So, I moved them back where they are supposed to be. The problem is, every time I try to restore my save data (if I can't do it, I can sorta redo it with save states) using save states, I get a message telling me that the save state was created using a different core. I do not get what this means, I did not delete my core. I was adding a different game and didn't even touch the data for this game. Is there any way to change back to the previous core or find out what core I've been using?? Again, I still have all the save states. It is a matter of getting the save states to work. Thank you for the help!! I hope I explained my issue well.

**Comment by luigi0301** [comment] 2018-07-04 09:24
For reference, I get a message that says "This save state was created with a different core. Do you want to switch to that core now?" but it won't switch to that core. When I click switch I get this message: "The operation couldn’t be completed. (OECoreUpdaterErrorDomain error -1.)" 

Again, thank you so much!!

**Comment by clobber** [comment] 2018-07-04 14:36
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3436

**Closed by clobber** 2018-07-04 14:36 UTC
