### ISSUE TITLE
(10.7 ?) Saved files window jams after trying to delete a file on 1.0.4

### ISSUE THREAD

**Issue by Savler** [OpenEmu/OpenEmu#1639] opened 2014-10-16 16:31 UTC
Since I updated to the last version (1.0.4), when I try deleting a file (clicking alt + the file I want to delete) it all seems to work well, but when I check out the files, the one I tried deleting is still there and from this moment on the window jams, making it impossible to disappear unless I quit OpenEmu.

If I try accessing the settings window it jams as well.
If I stop playing the game it is still there, and even if I close the app's main window it is still there, unless, like I said, I quit OpenEmu.

Please HELP.

Screen shots:

![screen shot 2014-10-16 at 17 27 51](https://cloud.githubusercontent.com/assets/9270636/4666250/c0765794-5551-11e4-9a11-a239f6013d9c.png)

![screen shot 2014-10-16 at 17 24 06](https://cloud.githubusercontent.com/assets/9270636/4666254/c5f00b98-5551-11e4-97e5-9196f5badc36.png)

![screen shot 2014-10-16 at 17 25 35](https://cloud.githubusercontent.com/assets/9270636/4669797/38065394-5571-11e4-8ccf-343f1083efa2.png)

greetings,
Savler

**Comment by Savler** [comment] 2015-02-13 14:43
It has been 4 months and still nothing!

**Comment by cyco** [comment] 2015-02-13 17:32
Hey there,
as i said, i can't reproduce this issue. Can you enable the secret settings and run a check on your database (https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets). Last button in the secrets pane. Please post the result here (can be found in Console.app)
You can also click on "Cleanup Save States" but be careful as that function might remove some states.

**Comment by astrange** [comment] 2015-02-25 01:54
If you have Console.app open while this happens, is anything suspicious printed mentioning OpenEmu? Especially exception or assertion failed.

**Comment by clobber** [comment] 2015-03-23 21:26
@Savler You never gave us important details such as which version of OS X you're running with this bug. Please specify.

**Comment by clobber** [comment] 2015-03-30 19:19
Closing, no additional info given.

**Closed by clobber** 2015-03-30 19:19 UTC
Labels: Need more information, UI, ⚑ Bug
