### ISSUE TITLE
Controls don't work

### ISSUE THREAD

**Issue by mrkingsly** [OpenEmu/OpenEmu#2577] opened 2016-06-07 11:06 UTC
I'm using OpenEmu on my MacBook Pro and it seems like my keyboard doesn't work at all with any game I play... how can I fix this issue?

**Comment by clobber** [comment] 2016-06-07 14:12
Need to use the search.

This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-06-07 14:12 UTC
