### ISSUE TITLE
N64 bluetooth controller (for Switch) will not map buttons or register inputs in OpenEmu 2.3.3 (or experimental) on macOS 13.0.1

### ISSUE THREAD

**Issue by beyondthecut** [OpenEmu/OpenEmu#4794] opened 2022-11-22 21:49 UTC
The  official switch online service N64 controller is recognized by macOS 13.0.1 as a bluetooth device, however the controller  will not map buttons or register inputs in OpenEmu 2.3.3
Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Hold the sync button on the controller
2. Open System Settings->Bluetooth and add the controller
3. Launch OpenEmu and in the "Controls" preferences area choose "N64 Controller"
4. Try to map the inputs
# Expected Behavior

1. Inputs all map (including analog)

# Observed Behavior

1. Inputs do not maps
2. NOTE: Apple Arcade titles *DO* detect the controller and they auto-map (e.g. Shovel Knight Dig) on macOS 13.0.1.
3. NOTE: Connecting the device directly over USB-C makes no difference to the outcome.
# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 13.0.1

**Comment by jeantichoc** [comment] 2022-12-27 01:32
I noticed the issue too.

I compare with Dolphin, and the button doesn't map either with the "Input/0/N64 Controller".
But the "SDL/0/Nintendo N64 Controller" works perfectly

![image](https://user-images.githubusercontent.com/473738/209596897-99d59169-23a5-4a62-8222-1eea0ba3c809.png)

So maybe it's a clue of the root cause.

**Comment by jeantichoc** [comment] 2022-12-27 01:37
Seems to be a duplicate of https://github.com/OpenEmu/OpenEmu/issues/4611

**Closed** 2022-12-27 20:41 UTC
Labels: duplicate
