### ISSUE TITLE
OpenEmu won't play games on opening or start

### ISSUE THREAD

**Issue by ryanmusicco** [OpenEmu/OpenEmu#4362] opened 2020-12-15 17:15 UTC
When opening a game save state quick save or restarting, OpenEmu will freeze and not play anything regardless of console. Also have to force quit Openemu as will not quit normally. Please help!, I miss the games!

[Openemu problem.mov.zip](https://github.com/OpenEmu/OpenEmu/files/5697468/Openemu.problem.mov.zip)

**Comment by shysaur** [comment] 2020-12-18 21:13
- Did you change your default audio output settings recently? There is a known issue with multi-output audio devices and applications like Soundflower. Try to set the default audio input/output devices to your internal speakers/microphone using "Audio MIDI Setup.app".
- If that didn't help, while OpenEmu is closed delete the folder "~/Library/Application Support/org.openemu.OEXPCCAgent.Agents". Reopen OpenEmu and check if the issue is fixed.

For now I am closing this issue; if none of these steps did work, feel free to open a new issue **but next time remember to specify the OpenEmu version and the macOS version you are using**.

**Closed by shysaur** 2020-12-18 21:13 UTC
