### ISSUE TITLE
OpenEmu not accepting any input from keyboard or dualshock 3 controller

### ISSUE THREAD

**Issue by WatermelonDriveway** [OpenEmu/OpenEmu#2566] opened 2016-05-31 02:36 UTC
I can't remap any of the controls, or use any of the default ones.

OpenEmu v 2.0.1
407-g415a4a6-Release

OS X El Capitan 10.11.3

**Comment by clobber** [comment] 2016-05-31 02:50
Need to use the search.

This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-05-31 02:50 UTC
