### ISSUE TITLE
Problem mapping a controller...

### ISSUE THREAD

**Issue by LinkGplus** [OpenEmu/OpenEmu#2564] opened 2016-05-28 02:34 UTC
When I map my controller to work with the PS1 emulator, it works fine, but after restarting the PC, the D-pad is mapped different... that happen every time I restart OpenEmu, and just with PS1 emulator...
Why is this happening?, What can I do to fix it?

**Comment by clobber** [comment] 2016-05-28 04:56
Dupe of #2395

**Closed by clobber** 2016-05-28 04:56 UTC
