### ISSUE TITLE
App not opening since recent update

### ISSUE THREAD

**Issue by nblackmo** [OpenEmu/OpenEmu#4421] opened 2021-01-10 03:52 UTC
I was playing on the app earlier today and things were working with no issue but then I downloaded and installed the most recent update and now the app won't even stay open. It quits and I get the error notice dialog explaining that the app has quit unexpectedly. If It hit reopen it just happens again. I've submitted multiples of these issues through the error dialog that sends the issue to Apple.

<img width="1440" alt="Screen Shot 2021-01-09 at 10 52 08 PM" src="https://user-images.githubusercontent.com/12863514/104113999-5c956500-52cd-11eb-9938-cc904399b459.png">

**Comment by clobber** [comment] 2021-01-10 04:26
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4410

**Closed by clobber** 2021-01-10 04:26 UTC
