### ISSUE TITLE
Yabause core: Radiant silvergun controls not working properly

### ISSUE THREAD

**Issue by schelliepellie** [OpenEmu/OpenEmu#2400] opened 2016-02-04 10:41 UTC
Dear hardworking people of Openemu,

I have been using Openemu for quite awhile now and am astonished by how amazing it is, great job guys! 

However I have one small issue with the particular Sega Saturn game called Radiant Silvergun. The game works just fine and runs smooth, but the controls keep locking up. By this I mean that certain buttons just keep active and other buttons won't correspond anymore except for the d-pad. This always happens after I press a certain attack button (the L1 button I believe). I did not see any related issues yet. 

- I am using a ps3 dual shock 3 controller that is properly set up via bluetooth and works fine in other games (other consoles)
- Am running El capitan 10.11.3
- Running Openemu v2.0.1, 407-g415a4a6-Release
- Have tried other controllers such as the keyboard and a wiimote (also properly set up!) with no result: still the same issue of certain controls just locking up.
- Other cores work just fine (Gameboy, SNES etc.) with the dual shock 3.
- I have tried another rom dump of the game, still the same control issue.

Besides this I have tried the usual: rebooting my mac and Openemu of course! Any ideas what might be the problem? I tried finding info if this is just a yabause specific problem with the game but didn't find anything, a couple of videos have the game running with no problems in any case..

UPDATE: late this day I tested another Saturn games (NiGHTS into dreams) and the controls worked perfectly, so it seems to be an isolated case with Radiant Silvergun?

**Comment by Solarstrike** [comment] 2016-02-15 16:00
Yabause is still a bit buggy and isn't compatible with everything, y'know.
That's why it's 'experimental'.

**Comment by schelliepellie** [comment] 2016-02-16 22:12
I obviously know it is experimental, hence me dressing an issue I have come across should anyone want to look into it ever.

**Comment by Solarstrike** [comment] 2016-02-17 04:37
@clobber?

**Comment by clobber** [comment] 2016-05-26 00:16
Dupe of #2048

**Closed by clobber** 2016-05-26 00:16 UTC
Labels: Core
