### ISSUE TITLE
Cover Art missing!!!

### ISSUE THREAD

**Issue by Shouse7** [OpenEmu/OpenEmu#1790] opened 2015-01-23 10:24 UTC
ALL cover art is now gone. I spent hours hunting for good covers too - now all gone! Why?

**Comment by cyco** [comment] 2015-01-23 12:04
Oh wow that sucks. You can blame me if that helps. If you'd like to recover your artwork instead i'll need some more info. Which version of os x and openemu do you use. Did you manually access your application support directory? Did you change the default location for openemu's library? Did you recently update openemu to a new version? Maybe you can even upload your 'Library.storedata' file.
Everything could help to fix the problem. Everything except for what you have given us.

**Comment by Shouse7** [comment] 2015-01-24 00:25
file is still the same - shouse > library > application support > openemu

yes I recently updated openemu it is at the latest.

mac osx 10.7.5 (not the newest version obviously.)

**Comment by Shouse7** [comment] 2015-01-24 00:26
I made all my art by either "git artwork" option within openemu, or click dragging google art to the rainbow box colors when art could not automatically be found. I have not modified files in any other way however.

**Comment by Shouse7** [comment] 2015-01-24 00:28
file size is 11 gb. do you really want me to upload?

**Comment by Shouse7** [comment] 2015-01-26 07:15
any update? Thanks for your help :) Is anyone else having this issue?

**Comment by cyco** [comment] 2015-01-26 09:57
Sorry, I've been a little busy over the weekend. I believe we've seen the same problem before (#1759). Are you sure the Library.storedata file is that big? The full path to the file is ~/Library/Application Support/OpenEmu/Game Library/Library.storedata

**Comment by Shouse7** [comment] 2015-01-26 10:30
github does not support that file type. only png, gif, and jpg. 
do you have an email i can send the file to?

**Comment by Shouse7** [comment] 2015-01-26 10:36
sending data file to christoph.leimbrock@gmx.de

**Comment by cyco** [comment] 2015-01-27 18:25
Confirmed dupe of #1759.

**Closed by cyco** 2015-01-27 18:25 UTC

**Comment by Shouse7** [comment] 2015-01-29 01:11
looked at the thread. Apparently what fixed it for him, did not fix it for me. Any way to downgrade to a prior version?

**Comment by Shouse7** [comment] 2015-01-29 01:16
I am thinking of just deleting all of the data to free up space. Will wait a few days, if the project has lost support then I guess that is only thing left to do.

**Comment by cyco** [comment] 2015-01-29 01:18
You didn't get my email?
The guy from the other thread manually added his artwork again.
Sadly, downgrading won't help. All artwork entries have been cleared out in the actual database file.

You can safely delete the 'Artwork' directory in your Game Library folder to free up space and then add new images.

**Comment by Shouse7** [comment] 2015-01-29 02:58
too bad I wasted all that time manually adding art in the first round.
Maybe future updates wont delete the art!!! LOL

Cheers, hope you guys find a way to get compensated for your $$$

I will donate when I am rich. ;)
promise

To our total freedom, with Ωmegaspeed,

~ King Tyler Von Durden Vendetta Shouse




                         ♕






                         ♕

King Tyler VVS 
Founding Father of
The Freedom Network

                           ♕







                           ♕

"The Truth Shall Set You Free."

                           ♕

www.d3fc.com ~ Durden's Daily Dividends and Free Coins

**Comment by Shouse7** [comment] 2015-01-29 03:13
I guess it is better than nothing.

I am pretty sure all future cover art will look like that, until a new update.
I will just refrain from using art for now haha.

Updates suck! half the time, they should be called DOWNDATES haha 

Cheers bud.=
