### ISSUE TITLE
How can I turn off automatic update

### ISSUE THREAD

**Issue by appoleo** [OpenEmu/OpenEmu#4484] opened 2021-03-29 10:10 UTC
Mame core will be automatically updated after openemu is started. How can I turn off automatic update? I had search the relevant content, but nothing be find, and I didn't find the relevant settings in openemu, please help me

**Comment by clobber** [comment] 2021-03-29 17:17
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4423

**Closed by clobber** 2021-03-29 17:17 UTC
Labels: question
