### ISSUE TITLE
OpenEmu creates additional windows when launching games

### ISSUE THREAD

**Issue by Soldier-2Point0** [OpenEmu/OpenEmu#3660] opened 2018-06-30 19:20 UTC
Launch game, swipe up with three fingers on trackpad (Mission Control), you will see ghost (blank) windows when you hover your mouse pointer over empty spaces on screen. 

The problem is that these windows keep accumulating the longer you keep playing different games and it forces OpenEmu main window bottom to start resizing up until you close the main program and reopen. 

Please advise.

**Comment by clobber** [comment] 2018-06-30 19:34
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3477

**Closed by clobber** 2018-06-30 19:34 UTC
