### ISSUE TITLE
Problème avance rapide 

### ISSUE THREAD

**Issue by ThomasDC70** [OpenEmu/OpenEmu#4781] opened 2022-10-29 05:39 UTC
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by ThomasDC70** [comment] 2022-10-29 05:39
Bonjour, je n'arrive le bouton "avance rapide" ne marche plus sur Mac depuis la mise jour MAC OS Ventura 13. Pouvez-vous m'aider ?

**Comment by clobber** [comment] 2022-10-30 02:46
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4780

**Closed by clobber** 2022-10-30 02:46 UTC
