### ISSUE TITLE
Experimental: Odyssey 2 games don't appear in O2 library.

### ISSUE THREAD

**Issue by peterb12** [OpenEmu/OpenEmu#1865] opened 2015-03-16 22:43 UTC
Repository state: Head of line master at commit 7b36bc895a4867613bb535bd9ca3d74a5c3713f6
Build state: Build All + Experimental / Release (but this happens for me in the 1.04 release build as well.)

Steps to reproduce:
(1) Have folder of Odyssey 2 .bin files.
(2) Drag folder (or individual file) to OpenEmu window.
(3) Go to problem resolution menu
(4) Select all
(5) In destination pulldown, choose "Odyssey 2"
(6) Click "Apply" button.

Results:
All imported files end up in the "unsorted" directory of the library.  Not visible in the Odyssey 2 library.

**Comment by clobber** [comment] 2015-03-17 08:03
Cannot replicate this.

I just drag and dropped the unzipped files "Cosmic Conflict (Europe).bin" and "Demon Attack (USA, Europe).bin" to the window, went to issue resolver, selected Odyssey 2 and they imported into the correct library.

**Comment by peterb12** [comment] 2015-03-17 15:31
Is there any logging I can turn on to try to understand why we see different results?

**Comment by clobber** [comment] 2015-03-19 07:46
No, you'd have to build for debug and see if there is any logging or possibly set a breakpoint to see what is going on. Can you try just drag and dropping one of the same plain .bin files again, making sure its unzipped?

**Comment by peterb12** [comment] 2015-03-19 21:29
Yeah, I tried that also.  I'll kick off a debug build and poke around.

**Comment by peterb12** [comment] 2015-03-20 12:20
Reproducing my steps below, with some more love from the debugger.

(1) Making sure it's not secretly a .zip:

Spartacus% file /Users/peterb/Desktop/Odyssey/Demon\ Attack\ \(USA\,\ Europe\).bin 
/Users/peterb/Desktop/Odyssey/Demon Attack (USA, Europe).bin: COM executable for DOS

(2) Ominous warning on startup:

3/20/15 7:21:26.565 AM OpenEmu[17864]: OELibraryDatabase loadFromURL: 'file:///Users/peterb/Library/Application%20Support/OpenEmu/Game%20Library/'
3/20/15 7:21:26.595 AM OpenEmu[17864]: OELibraryDatabase.m:233: -[OELibraryDatabase loadPersistantStoreWithError:]: ROMS folder url: ./roms/ -- file:///Users/peterb/Library/Application%20Support/OpenEmu/Game%20Library/
3/20/15 7:21:26.998 AM OpenEmu[17864]: OEApplicationDelegate.m:182: -[OEApplicationDelegate libraryDatabaseDidLoad:]: 

(but games still run, and I was able to successfully add a homebrew Sega Game Gear game)

(3) After adding:

3/20/15 7:26:03.200 AM OpenEmu[17864]: OEGameScannerViewController.m:348: -[OEGameScannerViewController romImporterDidStart:]: 
3/20/15 7:26:03.234 AM OpenEmu[17864]: OEROMImporter.m:528: -[OEROMImporter finish]: Finish
3/20/15 7:26:03.235 AM OpenEmu[17864]: OEGameScannerViewController.m:376: -[OEGameScannerViewController romImporterDidFinish:]: 
3/20/15 7:26:12.520 AM OpenEmu[17864]: OEGameScannerViewController.m:348: -[OEGameScannerViewController romImporterDidStart:]: 
3/20/15 7:26:12.691 AM OpenEmu[17864]: OEROMImporter.m:528: -[OEROMImporter finish]: Finish
3/20/15 7:26:12.692 AM OpenEmu[17864]: OEGameScannerViewController.m:376: -[OEGameScannerViewController romImporterDidFinish:]: 

(4) Spartacus% ls /Users/peterb/Library/Application\ Support/OpenEmu/Game\ Library/roms/unsorted
Demon Attack (USA, Europe).bin

(5) Running in the debugger, I see this (I think it's just a red herring, but mentioning it just the same)

2015-03-20 07:38:28.663 OpenEmu[24613:639540] Failed to connect (applyButton) outlet from (OEGameScannerViewController) to (OEButton): missing setter or instance variable

(6) Stepping into -resolveIssues in the debugger after clicking "Apply":

(lldb) po selectedSystem
openemu.system.odyssey2
(lldb) po item
<OEImportOperation: 0x618000102a30>{name = '(null)'}
(lldb) po [item importer]
<OEROMImporter: 0x6100002871c0>

(7) In -[OEImportOperation OE_performImportStepOrganize]:

The move operation fails because NSFileManager returns permission denied.  Which is weird, since I own the file and have appropriate permissions.  This happens even if I delete the Odyssey² folder and allow OpenEmu to re-create it.

(lldb) po error
Error Domain=NSCocoaErrorDomain Code=513 "“Demon Attack (USA, Europe) 6.44.20 PM.bin” couldn’t be moved because you don’t have permission to access “Odyssey²”." UserInfo=0x6180000fc500 {NSSourceFilePathErrorKey=/Users/peterb/Library/Application Support/OpenEmu/Game Library/roms/unsorted/Demon Attack (USA, Europe) 6.44.20 PM.bin, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/peterb/Library/Application Support/OpenEmu/Game Library/roms/Odyssey²/Demon Attack (USA, Europe) 6.44.20 PM.bin, NSFilePath=/Users/peterb/Library/Application Support/OpenEmu/Game Library/roms/unsorted/Demon Attack (USA, Europe) 6.44.20 PM.bin, NSUnderlyingError=0x6180002573a0 "The operation couldn’t be completed. Permission denied"}

If it matters, I'm running 10.10.2.

**Comment by peterb12** [comment] 2015-03-20 12:24
Possibly related to sandboxing?

http://stackoverflow.com/questions/13950476/application-sandbox-renaming-a-file-doesnt-work

**Comment by cyco** [comment] 2015-03-30 16:41
I can't reproduce this either. OpenEmu is not sandboxed so i don't think that's the issue.
What filesystem do you use?
You could try to change your region to Europe and see if importing the game as Videopac works for you.

**Comment by clobber** [comment] 2015-04-26 21:06
Abandoned; no info. Closing

**Closed by clobber** 2015-04-26 21:06 UTC
Labels: Need more information

**Comment by SEGADREAM** [comment] 2015-08-15 08:29
When you add games in go to the resolve issue section click odyssey2 make sure it is ticked.
