### ISSUE TITLE
Open Emu crashes with PPSSPP

### ISSUE THREAD

**Issue by chamrp** [OpenEmu/OpenEmu#2701] opened 2016-08-03 15:38 UTC
Hi,
I experienced crashes with several PSP games, always at the same place in the game (usually the very beginning, after one or two cutscene, before even being able to play). Did that with KH Birth by Sleep or Ratchet & Clank for instance.
At first I thought it was a PPSSPP issue but then I tried to play those games with their own software and it worked perfectly… 

When it crashes: the game freezes and OpenEmu won't respond to anything except the Full Screen/Window button.

Do you have any idea where I could look for to solve this? I can eventually play the game with this other solution but I'd really like to be able to do so in OpenEmu.

Thanks very much.

**Comment by clobber** [comment] 2016-08-03 17:37
You have to compare to the same version as PPSSPP standalone, as there could be regressions.

Since there is no build of PPSSPP 1.2.2 standalone out, we cannot investigate if this is an OpenEmu implementation bug or a regression in PPSSPP.

Dupe of #2621

**Closed by clobber** 2016-08-03 17:37 UTC

**Comment by chamrp** [comment] 2016-08-03 22:15
Thanks, I get it. Is there a way to manually downgrade the core in OpenEmu using a previous version of the ".oecoreplugin" available here? Sorry if that has been answered as well, couldn't find anything…

**Comment by clobber** [comment] 2016-08-06 17:11
Fixed in https://github.com/OpenEmu/PPSSPP-Core/commit/2e3463b49db1c45f4d2ae6e1554b99b41c2aa7ca. Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.2.2.1.

**Comment by chamrp** [comment] 2016-08-06 17:47
Seems to work fine! Thanks a lot.
