### ISSUE TITLE
Bios Problem

### ISSUE THREAD

**Issue by SimplyWillis** [OpenEmu/OpenEmu#2380] opened 2016-01-28 07:48 UTC
Hello. I've dropped my bios files into Open Emu and I am still having trouble playing ps1 games. I have searched every thread I could find on the matter, and none seem to help. I've checked all the md5 tags for my files and they match perfectly those in the bios guide. The game I am trying to play is Digimon World. It loads up the Sony Entertainment logo then the PS logo and then hits me with "Video mismatch error." Any ideas as to what else I could be doing to cause this? How do I find where openemu stores bios files and delete them, so that I can put the same ones back in fresh, just in case it is not updating to the newest ones I have with the correct md5 tags (as one of the initial ones did not).

Thanks in advance!
-SW

**Comment by clobber** [comment] 2016-01-28 08:13
Sounds like a bad rip of the game or possible emulator bug. Nothing we can do for you right now, and your BIOS files are fine assuming you are using OpenEmu 2.0.1

Duplicate of #2274

**Closed by clobber** 2016-01-28 08:13 UTC
