### ISSUE TITLE
Hat switch devices: Input Problems

### ISSUE THREAD

**Issue by AugDaug** [OpenEmu/OpenEmu#2395] opened 2016-02-01 02:52 UTC
Hi Guys--

I recently upgraded from Mountain Lion to El Capitain, and then from OpenEmu 1.0.4 to 2.0.4.

I'm seeing a new issue now: when I map my controls (to an old PS2 controller with a USB adapter, which has always worked), they don't get saved properly. It's strange; if I quit the app, the next time I open it, the mappings have changed slightly. For the D-Pad, North/South & East/West get flip-flopped, so that up is now west, down is east, etc. I can map the controls back to normal, play games, and all is good, until the next time I open the app, and then they've swapped again. The other buttons seem to be saved properly. Doesn't make the app unusable; it's just a pain to have to remap some of the buttons EVERY time I want to play.. Anybody else see this, or have any insights on how to fix?

Thanks.

**Comment by cedwardsmedia** [comment] 2016-04-04 20:34
I've been encountering this non-stop since the update to 2.x. It happens for my PS3 Wireless Controller. Pretty annoying.

**Comment by jndev** [comment] 2016-04-30 15:44
Same issue with the Hori Pokken Controller. In my case, I was able to solve it by adding a mapping for this controller in the Controller-Database.plist file.

**Comment by clobber** [comment] 2016-04-30 16:33
We're aware of this issue for devices that use a hatswitch and have a possible fix. I'd like to get a HID profile of your devices so I can take a look.

With your device connected, run this app http://cl.ly/2K1K400t0H3p

Select your gamepad from the list and then go to File > Export Device Properties and then give us the plist it generates, by uploading to cloudapp, dropbox, transfer.sh, etc.

**Comment by jndev** [comment] 2016-05-03 19:29
Here is the HID profile of the Hori Pokken Controller: https://www.dropbox.com/s/i7mgwgql8zf747b/POKKEN%20CONTROLLER.plist?dl=0

**Comment by clobber** [comment] 2016-05-03 20:06
@jndev
>The file you’re looking for has been moved or deleted.

**Comment by jndev** [comment] 2016-05-03 20:11
Should be fixed.

**Comment by claudechinsta** [comment] 2016-06-23 00:08
I can understand the problem is the "Hat switch". After checking the device by HIDbrowser, I found it that my 8bitdo controller set its "D-pad" as "hat switch". So if there are pre-setting that we can find out and edit or is there any other methods? :)

**Comment by clobber** [comment] 2016-07-01 07:55
Fixed in https://github.com/OpenEmu/OpenEmu-SDK/commit/f8b45751afadb936c5e1df47914d5061dfb5f2a8 for next version.

**Closed by clobber** 2016-07-01 07:55 UTC
Labels: Input
