### ISSUE TITLE
Suggestion: controller renaming

### ISSUE THREAD

**Issue by edrozenberg** [OpenEmu/OpenEmu#3827] opened 2018-12-24 22:37 UTC
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Add a controller for which the automatic naming doesn't make sense. For example, my 8Bitdo SN30 shows up as "Sony PS4 DualShock Wireless". This causes confusion because I also connect an actual PS4 controller, which shows up as "Sony PS4 DualShock Wireless (CUH-ZCT2)". And it would just be nice to be able to assign the actual controller name.

# Expected Behavior

1. Provide a feature/method to rename controller to reflect the actual controller name, or desired user name.

# Observed Behavior

1. Some controllers automatically are named as for ex. "Sony PS4 DualShock Wireless" even though they are something completely different.

# Debugging Information

- OpenEmu Version: v2.0.8 016-g31a4fbf-Release
- macOS Version: 10.14.3 Beta (18D32a)

**Comment by edrozenberg** [comment] 2018-12-24 22:39
This is not related to the Bluetooth names - I was able to change the Bluetooth names for these controllers as I prefer in Apple Bluetooth prefs.

**Comment by clobber** [comment] 2018-12-25 21:34
>Some controllers automatically are named as for ex. "Sony PS4 DualShock Wireless" even though they are something completely different.

Stop using 8bitdo's incorrect "Mac mode" when you pair their devices. Power on with START, **not** START+A.

As for the rest of this:

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #1723

**Closed by clobber** 2018-12-25 21:34 UTC
