### ISSUE TITLE
Label display issue

### ISSUE THREAD

**Issue by livid** [OpenEmu/OpenEmu#4074] opened 2019-12-30 01:27 UTC
Those labels are not aligning/displaying correctly:

- Library: Drag & Drop Games Here
- Screenshots: No Screenshots Found
- Homebrew: Fetching Games

Screenshots are attached.

<img width="977" alt="Screen Shot 2019-12-29 at 5 23 18 PM" src="https://user-images.githubusercontent.com/11427/71565122-22f61100-2a60-11ea-8ef0-fbb2fd550d8d.png">
<img width="977" alt="Screen Shot 2019-12-29 at 5 23 21 PM" src="https://user-images.githubusercontent.com/11427/71565118-1376c800-2a60-11ea-8987-fb571e964b4d.png">
<img width="977" alt="Screen Shot 2019-12-29 at 5 23 29 PM" src="https://user-images.githubusercontent.com/11427/71565137-62bcf880-2a60-11ea-9b95-de03167955fd.png">

# Steps to reproduce

That label display issue appeared a while ago. I tried to reinstall, but it persisted. Fresh install on a new Mac does not have the problem.

# Debugging Information

- OpenEmu Version: 2.2
- macOS Version: 10.14.6

**Comment by clobber** [comment] 2019-12-30 01:30
This appears a duplicate of #3920 

@robotoad and myself are unable to replicate this, so perhaps there are certain conditions or more details you could provide. Please add further discussion in issue #3920 though.

**Closed by clobber** 2019-12-30 01:30 UTC
Labels: duplicate
