### ISSUE TITLE
fast forward not working

### ISSUE THREAD

**Issue by Bcap32** [OpenEmu/OpenEmu#4814] opened 2022-12-25 11:36 UTC
I play pokemon on openemu a lot. The fast forward function does not work anymore. just fast forward is not working. 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

- OpenEmu Version: v2.3.3
- macOS Version: 13.1

**Comment by clobber** [comment] 2022-12-25 15:26
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

This is fixed for next release.

Duplicate of #4780

**Closed by clobber** 2022-12-25 15:26 UTC
