### ISSUE TITLE
FS UAE Core

### ISSUE THREAD

**Issue by promythyus** [OpenEmu/OpenEmu#1841] opened 2015-02-24 02:17 UTC
Is it within the scope of this project to add support for an FS UAE core for supporting Amiga emulation? If so, any chance we'll see some work on it?

https://github.com/FrodeSolheim/fs-uae

**Comment by clobber** [comment] 2015-02-24 03:11
Sorry, no. That doesn't fit in well with our model.

Also dupe of #1372

**Closed by clobber** 2015-02-24 03:11 UTC
