### ISSUE TITLE
wiimote nunchuck analog stick sensitivity significantly too low

### ISSUE THREAD

**Issue by telverston** [OpenEmu/OpenEmu#3537] opened 2018-02-21 01:39 UTC
Greetings,

I know that there are bleeding-edge builds of OpenEmu which are attempting to remedy the analog stick sensitivity issues.  Older builds of OpenEmu worked perfectly with my USB adapter for my original N64 controller, but I suppose since the switch-over to mupen64plus core has affected the calibration, as noted in:
[#1303](https://github.com/OpenEmu/OpenEmu/issues/1303)

However, I have read and read in circles here to find out how to adjust, or solve the issues for the controllers for my N64 games playing in OpenEmu.  Is there a solution?  I am getting an output of only 59 with a wiimote analog stick on the nunchuck, and only up to 40 with the N64 original controller.  These are stick values that I see when using the "glankk practice rom" of zelda OoT—it shows them at the bottom.  The 1.0 OoT rom also exhibits the "walking only" behavior.

I understand that original N64 controllers are supposedly not supported through a USB adapter, and the wiimote, while it can be officially paired and mapped to the N64 controller core, will still not output a full range that would allow Mario or Link to do anything other than walk slowly.

What can I do?  What controller setup is most-supported for mupen64plus?  Original N64 controller used to work splendidly.

Thanks!!!  Love the work you're doing.

**Comment by clobber** [comment] 2018-02-21 01:53
> I know that there are bleeding-edge builds of OpenEmu which are attempting to remedy the analog stick sensitivity issues

No there are not.

> Older builds of OpenEmu worked perfectly with my USB adapter for my original N64 controller

That was not OpenEmu related, but related to a Mupen64Plus core plugin update that fixed a bug with analog input. It only sort of "worked" with certain gamepads before, but was actually incorrect. More info on this in #3102.

> What can I do? What controller setup is most-supported for mupen64plus?

The workaround for now would be to use another analog gamepad such as DualShock 3, DualShock 4, SteelSeries Nimbus or other MFi device, 8Bitdo NES30 Pro, 8Bitdo SN30 Logitech F310, Logitech Dual Action or Nintendo Wii U Pro. Avoid the Nintendo Switch Pro and N64 adapters.

Your issue is a duplicate of #3102 and we don't need more of these open.

**Closed by clobber** 2018-02-21 01:53 UTC
Labels: duplicate

**Comment by telverston** [comment] 2018-02-21 15:01
So, opening this report was the last-resort thing I did.  

From the main webpage, it lists the wiimote as supported.  Had the main web page mentioned that it is supported with *known issues, I would never have written here.  If there are many duplicate bug reports cropping up, perhaps the [learn more about controllers] link should mention that—yes, you can pair a wiimote, but the stick won't function properly. This would've stopped me, and likely many others.  I used the bug report after reading for about an hour, going in circles from bug to bug, and trying to piece together the real story.  I made an image that would've saved me, and maybe you, heaps of time and frustration.  
 
Not meant as criticism!  Thank you again.

![suggestion-openemu-site](https://user-images.githubusercontent.com/9355944/36486840-84d3050a-16ed-11e8-861f-3c13d6bdfcc8.png)
