### ISSUE TITLE
Helper application issues

### ISSUE THREAD

**Issue by Phdizzy** [OpenEmu/OpenEmu#4225] opened 2020-05-29 15:39 UTC
All the ROMS i used to run will not run anymore (atari 2600, N64, NES) "Couldn’t communicate with a helper application." I've tried installing BIOS files and nothing, I've tried clean re-installs and nothing. Please review the attached crash report.
[Crash.txt](https://github.com/OpenEmu/OpenEmu/files/4702773/Crash.txt)

**Comment by clobber** [comment] 2020-05-29 20:09
Do not delete the [issue template](https://github.com/OpenEmu/OpenEmu/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4165

**Closed by clobber** 2020-05-29 20:09 UTC
