### ISSUE TITLE
Game window is empty with macOS 10.14.1 Beta

### ISSUE THREAD

**Issue by stephenyeargin** [OpenEmu/OpenEmu#3769] opened 2018-10-20 04:03 UTC
While I know that OpenEmu only supports generally available versions of macOS, I wanted to file this issue as a heads up that a future version of the OS may cause issues.

# Steps to reproduce

1. Launch OpenEmu
1. Double-click a game (any platform)

# Expected Behavior

1. Game should load in window

# Observed Behavior

1. Empty gray window.
1. No other errors appear to the user

![screen shot 2018-10-19 at 10 54 38 pm](https://user-images.githubusercontent.com/80459/47251016-36d0cc80-d3f2-11e8-8fe2-727344693bad.png)

# Debugging Information

- **OpenEmu Version:** v 2.0.7 (968-gf66035e-Release)
- **macOS Version:** 10.14.1 Beta (18B67a)

```
error	23:01:01.757765 -0500	OpenEmuHelperApp	Unable to load Info.plist exceptions (eGPUOverrides)
error	23:01:01.796104 -0500	tccd	Failed to copy signing info for 4619, responsible for file:///Applications/OpenEmu.app/Contents/MacOS/OpenEmu: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
```

# Things I Have Attempted

1. Re-launched the application
1. Rebooted the computer

**Comment by clobber** [comment] 2018-10-20 04:05
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3768

**Closed by clobber** 2018-10-20 04:05 UTC
