### ISSUE TITLE
Keyboard controls not working

### ISSUE THREAD

**Issue by Oblisseron** [OpenEmu/OpenEmu#2523] opened 2016-04-28 07:26 UTC
I have updated my computer and reinstalled the application but once the rom starts running I can not hit any keys. I cannot change any controls either. I know there must be something that is causing this I just cant figure it out

**Comment by Oblisseron** [comment] 2016-04-28 07:27
This for the Gameboy advanced emulator so far.

**Comment by clobber** [comment] 2016-04-28 07:40
This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-04-28 07:40 UTC
