### ISSUE TITLE
Change Language on Gamecube System

### ISSUE THREAD

**Issue by GianGus** [OpenEmu/OpenEmu#4106] opened 2020-01-26 23:48 UTC
Hello,
it's a really welcome addition the Gamecube system on OpenEmu! Good job!
Is there a way to change the Gamecube system language so that the European games are in the selected language and not in standard English?
I'm italian and I've tried Animal Crossing/Paper Mario PAL EU version but they are in english and it's not possible to change language in the game, the system setting is the only one that permits this change.

Thank you

**Comment by clobber** [comment] 2020-01-27 03:38
Sorry, not possible to do this yet. That will come in the future when there are advanced per-core preferences available.

Somewhat a dupe of #1083

**Closed by clobber** 2020-01-27 03:38 UTC
