### ISSUE TITLE
help with open emu crashing

### ISSUE THREAD

**Issue by Tay2823** [OpenEmu/OpenEmu#3223] opened 2017-06-16 01:22 UTC
![screen shot 2017-06-15 at 8 17 11 pm](https://user-images.githubusercontent.com/29471313/27207943-1a4431e6-5208-11e7-8761-eb147fa12113.png)
So i followed everything as i have done with games multi disk games prior but for some reason it crashes when i try and add the file to the library.

**Comment by clobber** [comment] 2017-06-16 02:26
Dupe of #3153, read for solution.

**Closed by clobber** 2017-06-16 02:26 UTC
