### ISSUE TITLE
Joypad Legacy Not Working with OpenEmu 

### ISSUE THREAD

**Issue by mikerecordman** [OpenEmu/OpenEmu#2337] opened 2016-01-09 03:31 UTC
I've recently downloaded version 2.0.1 of OpenEmu (The experimental one that includes the PSX emulator). However, I can't get Joypad to work with OpenEmu.
I've downloaded Joypad Legacy for my iPhone and Joypad Connect for my Mac.
I've been able to connect Joypad to my Mac.
I've mapped out the controls in Joypad connect and made sure they matched the keys mapped in OpenEmu.
I've pulled up TextEdit on my Mac and have verified that when the buttons are hit in Joypad that they are typing out the corresponding keys. (i.e. I hit the X button on Joypad and X is being typed out in TextEdit).
I'm not sure why the game window isn't responding to the controls. I found an issue related to this in 2013 (issue 924). But it seems odd to me as it points out that the D pad is still working where none of my buttons work including the D pad.
Can anyone help me figure this out?

**Comment by clobber** [comment] 2016-01-09 20:15
Please search before opening a new issue.

Duplicate of #924

**Closed by clobber** 2016-01-09 20:15 UTC

**Comment by mikerecordman** [comment] 2016-01-09 20:39
What's the answer to the problem. How do I get it working?

**Comment by UOCecalero** [comment] 2016-03-27 13:05
I think that by the way is not working in the current version. Is not working to me as well.
Please, if the problem is solved, let us know. Thanks for your time.
