### ISSUE TITLE
Keyboard Not Working

### ISSUE THREAD

**Issue by cg011** [OpenEmu/OpenEmu#2526] opened 2016-04-29 23:16 UTC
Keyboard will not work, regardless of any attempt.

**Comment by clobber** [comment] 2016-04-29 23:52
Need to use the search.

This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-04-29 23:52 UTC
