### ISSUE TITLE
`Contra: Hard Corps` using code makes screen turn red/freeze.

### ISSUE THREAD

**Issue by inspiredlabs** [OpenEmu/OpenEmu#4805] opened 2022-12-12 18:43 UTC
`Contra: Hard Corps` using GameGenie code makes screen turn red/freeze.

I am raising this issue after I noticed [Any way to delete a cheat code?](https://www.reddit.com/r/OpenEmu/comments/3xt57e/any_way_to_delete_a_cheat_code/), and [this](https://github.com/OpenEmu/OpenEmu/issues/782#issuecomment-161443592) from a couple of searches.

# Steps to reproduce

1. Add a code
1. Tap the reset icon
1. `Contra: Hard Corps` using GameGenie code (`this-format`) makes screen turn red/freeze.
1. the game can't restart until the toggle is off.
1. then when in the game the toggle is turned on again – it works as expected.

# Expected Behavior

1. Perhaps an `x` or `delete` on the right-hand side of the modal next to each code would be sufficient from a UI standpoint? That would mean that if you need to rename each code, you could simply delete each and start from scratch.
1. Perhaps a `rename` and `delete` option would make the modal very wide. In this case an `edit` button would be favorable. 
1. Why the need for `rename`? As is often the case configuring codes learning controls/making life easy for the kids: `Easy: invincibility`, or `V. hard: no continues` is a clean use of the UI.

# Observed Behavior

1. poor naming conventions make the UI cluttered (eg: paste the code in twice for speed – now you don't know what each code does!).
1. the game can't restart until the toggle is off for each code.
1. multiple requests from different sources over this issue eg: [Reddit](https://www.reddit.com/r/OpenEmu/comments/3xt57e/any_way_to_delete_a_cheat_code/) and [this](https://github.com/OpenEmu/OpenEmu/issues/782#issuecomment-161443592).

- OpenEmu Version: `v2.3.3, 6866.4-g70ac442b-Release`
- macOS Version: `Ventura, macOS 13`.

**Comment by clobber** [comment] 2022-12-12 19:34
>using GameGenie code makes screen turn red/freeze

That is probably an upstream core plugin issue; not our bug. I need the cheat code you are using in order to test.

**Comment by clobber** [comment] 2022-12-14 23:20
Hi, if you can provide details as to which version (ROM) of the game and the valid cheat code (known to be working?) used that causes the freeze, I can look into this. Otherwise this is a duplicate of #3968 -- we aware the that cheats need improvement and have stated we plan for a cheat code manager UI.

**Closed** 2022-12-28 08:18 UTC
Labels: duplicate
