### ISSUE TITLE
Change Language in Zelda Twilight Princess on Gamecube

### ISSUE THREAD

**Issue by jeromepiedon** [OpenEmu/OpenEmu#4113] opened 2020-02-01 21:11 UTC
Hello everyone, i just add the possibilty to play Gamecube Game on my Openemu with my Macbook pro.

I  Download Zelda WW and Mario Sunshine, when i launched those games they were in English but i can go to the settings in this game to put them in French. My language ;)

THEREFORE, there is not those kind of settings in Zelda Twilight Princess I download the European Version and it is everytime in English, what is the process to have a French Language in Gamecube game in the European Version, hope you have the solution it is my favorite game :)

Have a nice day ;)

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment] 2020-02-01 21:24
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4106

**Closed by clobber** 2020-02-01 21:24 UTC
Labels: duplicate
