### ISSUE TITLE
Can you provide a way to update cores independant of app?

### ISSUE THREAD

**Issue by pleasejustgo** [OpenEmu/OpenEmu#4562] opened 2021-07-24 18:45 UTC
It's especially problematic with mame because when you update OpenEmu a mame rom may suddenly stop working becuaue it's the wrong set. I can't find the proper version of the rom I want to play, only the latest few versions are obtainable.

**Comment by clobber** [comment] 2021-07-25 00:29
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4423

**Closed by clobber** 2021-07-25 00:29 UTC
Labels: duplicate
