### ISSUE TITLE
Controller not recognized for 32X games

### ISSUE THREAD

**Issue by DarthMaliss** [OpenEmu/OpenEmu#1854] opened 2015-03-07 03:17 UTC
I'm using both a PS3 DS3 controller, and PS3 clone USB controller, and unfortunately neither work when trying to play 32X games. They do work with Genesis, as well as other emulators. The keyboard isn't working either.

I came across a similar post from last year: https://github.com/OpenEmu/OpenEmu/issues/1013 And it says it's been fixed, but I still have this issue. Thanx.

Running OpenEmu 1.0.4 on a 2011 Macbook Pro with Yosemite.

**Comment by clobber** [comment] 2015-03-08 02:44
You are saying input does not respond at all for that system? Try deleting your Default.oebindings file first in ~/Library/Application Support/OpenEmu/Bindings Configurations

**Comment by DarthMaliss** [comment] 2015-03-08 17:31
OK. Not home right now but I'll try it tomorrow and post back. Thanx.

**Comment by DarthMaliss** [comment] 2015-03-10 15:51
OK, deleted that file and rebooted. Still doesn't work for the keyboard of controller.

**Comment by clobber** [comment] 2015-03-11 05:23
Doesn't sound right to me, since I cannot reproduce this. I have the picodrive core version 1.91.1 and I can use controls for both keyboard and gamepad in-game. As well as any other system.

Is this with a particular game only?

**Comment by DarthMaliss** [comment] 2015-03-12 14:11
It appears it's just not working with one game, Star Wars Arcade.

**Comment by clobber** [comment] 2015-03-26 23:56
Closing, cannot replicate. Input for that game works fine for me.

**Closed by clobber** 2015-03-26 23:56 UTC
