### ISSUE TITLE
Can't save game state on GameCube

### ISSUE THREAD

**Issue by enriqueto** [OpenEmu/OpenEmu#4190] opened 2020-04-19 18:36 UTC
- OpenEmu Version: v2.2.1
- macOS Version: Catalina, v10.15.4

![Screenshot 2020-04-19 at 20 33 03](https://user-images.githubusercontent.com/5557196/79696499-5e218780-827d-11ea-834e-afbd836d8975.png)

**Comment by clobber** [comment] 2020-04-19 18:58
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4119

**Closed by clobber** 2020-04-19 18:58 UTC
