### ISSUE TITLE
Keyboard not working 

### ISSUE THREAD

**Issue by Marsterdam** [OpenEmu/OpenEmu#1876] opened 2015-03-26 22:03 UTC
First of all... I'm a complete computer nono... 

I discovered OpenEmu after a search for an emulator... But now I'm experiencing a difficulty with the keyboard not working 'in-game'. 

I downloaded OpenEmu from opener.org on a MacBook Pro (2011), 10.10.2.

Looking for help...

**Comment by clobber** [comment] 2015-03-26 23:47
This has come up several times in the past, usually related to some other open application causing interference. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2015-03-26 23:47 UTC
