### ISSUE TITLE
Plans for Wii support with dolphin

### ISSUE THREAD

**Issue by jcampbell05** [OpenEmu/OpenEmu#4128] opened 2020-02-17 02:35 UTC
Any plans to support the wii asa core using dolphin ?

**Comment by clobber** [comment] 2020-02-17 04:15
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4099

**Closed by clobber** 2020-02-17 04:15 UTC
Labels: duplicate
