### ISSUE TITLE
Emu not Codesigned

### ISSUE THREAD

**Issue by szippy** [OpenEmu/OpenEmu#3930] opened 2019-06-10 16:10 UTC
I just downloaded Open Emu from here: https://openemu.org/ and found that it isn't signed for OSX! I know apple has a path to getting a codesign certificate for free for nonprofits, which I linked below. Any chance we can get this codesigned? I'd be happy to help

https://developer.apple.com/support/membership-fee-waiver/

![image](https://user-images.githubusercontent.com/41277066/59209210-f92ed880-8b67-11e9-9010-cd89f94618e8.png)

**Comment by clobber** [comment] 2019-06-10 16:14
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

...and lol this is not an "eligible non-profit organization" -- actually read that webpage you link.

Duplicate of #816

**Closed by clobber** 2019-06-10 16:14 UTC
Labels: duplicate
