### ISSUE TITLE
Window does not close properly 

### ISSUE THREAD

**Issue by Azonnali** [OpenEmu/OpenEmu#3554] opened 2018-03-07 15:01 UTC
Having an OpenEmu game run at fullscreen, the game window does get smaller and closes its fullscreen space when you end the game yet the last frame of the game remains on screen and covers the space where OpenEmu is open (can be in either fullscreen or desktop). The bug does not occur when the game doesn't run in fullscreen
![openemubugreport](https://user-images.githubusercontent.com/37149444/37099498-b64d8b1c-2220-11e8-8fe3-53bd0d96162f.png)

**Comment by clobber** [comment] 2018-03-07 15:25
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

This is a bug already fixed for next release. Duplicate of #3479

**Closed by clobber** 2018-03-07 15:25 UTC
