### ISSUE TITLE
yobo usb controller(s)

### ISSUE THREAD

**Issue by heyuimintojsus** [OpenEmu/OpenEmu#2499] opened 2016-04-17 21:11 UTC
I have a Yobo usb controller for the NES and SNES. The NES seems to work - haven't tried the other yet - but when I try to pair 'down,' during the game it wants to go left or right, and I hit straight down on the controller. And ideas or input? Thanks in advance.

**Comment by clobber** [comment] 2016-05-26 00:31
Dupe of #2395

**Closed by clobber** 2016-05-26 00:31 UTC
