### ISSUE TITLE
OpenEmu 2.0.2 - Save States not working in Arcade

### ISSUE THREAD

**Issue by igarikoitz** [OpenEmu/OpenEmu#2609] opened 2016-07-03 13:59 UTC
Every time I finish playing an arcade game, OpenEmu automatically saves state. When I go to the Save State section and I try to load the saved game, the screen goes black and the application no respond.

**Comment by clobber** [comment] 2016-07-03 14:04
Using which gamepad?

**Comment by clobber** [comment] 2016-07-03 14:05
Forgot to mention - some Arcade games/systems in MAME don't save states properly, and aren't really supported.

**Comment by clobber** [comment] 2016-07-03 14:06
Closing due to that and the 'experimental' status of MAME support.

**Closed by clobber** 2016-07-03 14:06 UTC

**Comment by clobber** [comment] 2018-09-09 04:03
This was a duplicate of #2615 and has been fixed.
