### ISSUE TITLE
Arcade (Mame) only working once.

### ISSUE THREAD

**Issue by fedekrum** [OpenEmu/OpenEmu#3559] opened 2018-03-11 20:01 UTC
I am using 2.0.6.1 experimental. I can install games and play them.
But when I quit the game and try again, I get a black screen and have to Force Quit OpenEmu.
If I delete the game rom , and re install it, I can play once again and the same thing happends.

**Comment by clobber** [comment] 2018-03-11 20:40
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md)
- "Please search before opening a new issue."
- "Arcade/MAME is unsupported because it is an experimental core port and has inherent usability and maintainability issues. It is recommended to use the official [standalone](http://bamf2048.github.io/sdl_mame_tut/) version and to read this helpful [MAME ROMs tutorial](http://choccyhobnob.com/articles/demystifying-mame-roms/)."

Duplicate of https://github.com/OpenEmu/OpenEmu/issues/2615#issuecomment-230357101

Duplicate of https://github.com/OpenEmu/UME-Core/issues/7

**Closed by clobber** 2018-03-11 20:40 UTC
