### ISSUE TITLE
Won't allow keyboard action

### ISSUE THREAD

**Issue by BDanecker** [OpenEmu/OpenEmu#2565] opened 2016-05-28 15:15 UTC
I have downloaded the emulator today, and once i download a rom successfully, i continue to the game, but the game does not recognize ANY keyboard controls whatsoever. I went to "controls" to change the keyboard actions, but it will not even let me change the keys tied to the actions! I have seriously pressed every button on the keyboard while at the game (Pokemon Yellow) and nothing has given a response. I downloaded another game (Fire-red) and it has the same outcome. They both use Gameboy Advanced, and I am using a MacBook Pro.

**Comment by clobber** [comment] 2016-06-03 14:00
Need to use the search.

This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-06-03 14:00 UTC
