### ISSUE TITLE
Tens of invisible windows open on Expose View for Mac

### ISSUE THREAD

**Issue by twinters1** [OpenEmu/OpenEmu#3741] opened 2018-09-19 13:26 UTC
I am currently using OpenEmu on a MacBook Pro, and when i use the F3 key (Expose View), I see tons of invisible windows taking up a whole bunch of room under the name OpenEmu. If I click on any of these windows to access them, it takes me back to whatever current window I was previously in, say Google Chrome for example, and it does not delete this said invisible window. The only thing giving it away is the highlighted box around them when I mouse over each box, otherwise they are completely transparent. Any suggestions as to how to remove these windows?

**Comment by clobber** [comment] 2018-09-19 15:05
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3477

**Closed by clobber** 2018-09-19 15:05 UTC
