### ISSUE TITLE
Binding Dualshock 4 Triggers (L2 R2)

### ISSUE THREAD

**Issue by craciant** [OpenEmu/OpenEmu#3809] opened 2018-12-03 02:46 UTC
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Dualshock 4 controller is connected via official sony wireless adapter
2. Openemu launched
3. Open Preferences
4. Attempt to bind buttons

# Expected Behavior

1. Buttons bind successfully

# Observed Behavior

1. When attempting to bind L2, the Depress and Release are registered separately interfering with the binding process.
2. L2 gets bound to depress, R1 gets bound to release
3. Attempting to click on back to rebind keys results in being unable to bind any buttons without closing and relaunching openemu

# Debugging Information

- OpenEmu Version: 2.0.7
- macOS Version: 10.11.6

**Comment by clobber** [comment] 2018-12-03 02:48
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of # 2788

**Closed by clobber** 2018-12-03 02:48 UTC
