### ISSUE TITLE
psp game europe version

### ISSUE THREAD

**Issue by infinity1000** [OpenEmu/OpenEmu#4144] opened 2020-03-13 00:37 UTC
I downloaded the European version of the game (English, French, Italian, Spanish, etc ...) but when I start the game the language is preset in English, instead with the games where you can choose the language you can choose the one I prefer. I have read a guide on this forum but it is not valid for the psp emulator. Please help me !!

**Comment by clobber** [comment] 2020-03-13 00:43
As noted in previous issues, the option to select languages from the UI does not exist yet. Nothing you can do.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #1083

**Closed by clobber** 2020-03-13 00:43 UTC
