### ISSUE TITLE
Won't read any keyboard inputs

### ISSUE THREAD

**Issue by TEHCritMastr1** [OpenEmu/OpenEmu#2032] opened 2015-08-28 15:41 UTC
Whenever I run a game and play with the keyboard, it wouldn't read any of my inputs at all.  I first thought it was the keys I were specifically using, but when I tried to reassign keys, it wouldn't read those inputs as well.  Any feedback is appreciated.

**Comment by clobber** [comment] 2015-09-13 02:21
This has come up several times in the past, usually related to some other open application causing interference. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2015-09-13 02:21 UTC
