### ISSUE TITLE
OpenEmu freezes up entirely when emulation starts, without any discernible pattern

### ISSUE THREAD

**Issue by iggykidd** [OpenEmu/OpenEmu#4178] opened 2020-04-12 04:17 UTC
I can open the program fine, and manage my roms, but as soon as I start emulation of anything, it's just frozen.

No audio, just the first frame of whatever intro animation the game has, frozen indefinitely. 

If I try to close it, I get the same "do you want to stop emulation" prompt as normal, but clicking "yes" does nothing. If I try to quit OpenEmu, nothing happens. 

It remains frozen until I force quit the program. One thing to note, in the "force quit" window, it does not say that OpenEmu is "not responding".

This has happened with GBA games and N64 games. I have not tested it with any other games.

I will restart the computer, both hard and soft, and see no change when I reopen OpenEmu. Then, after a seemingly random number of restarts (generally three or more), it will start functioning normally again, with no issues.

My system:

MacOS Mojave 10.14.6
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
Processor - 2.9 GHz Intel Core i5
Memory - 8 GB 2133 MHz LPDDR3
Graphics - Intel Iris Graphics 550 1536 MB

OpenEmu v2.2.1
6136.54-g90714f36-Release

Update:
I have uninstalled and reinstalled the emulator multiple times now.
I have deleted every single file off my computer, manually, that is related to OpenEmu before reinstalling it.
No change.

**Comment by BakaByte** [comment] 2020-05-29 15:41
I had the exact same problem. Same 1 frame freeze, unable to quit except with force quit and it's not saying "not responding"

Try changing your Audio output. I had it set to a multi output device for my Audio Interface plus my HDMI monitor. Changing it to a single output worked for me

**Comment by iggykidd** [comment] 2020-05-29 18:57
> I had the exact same problem. Same 1 frame freeze, unable to quit except with force quit and it's not saying "not responding"
> 
> Try changing your Audio output. I had it set to a multi output device for my Audio Interface plus my HDMI monitor. Changing it to a single output worked for me

This does work, yep. I had a completely different multi output (audio interface and ishowu audio capture), so looks like the multi output as an option specifically causes the issue.

**Comment by clobber** [comment] 2020-05-29 20:12
Duplicate of #4055, #4165

**Closed by clobber** 2020-05-29 20:12 UTC
