### ISSUE TITLE
Updated Openemu and it moved my save files to the trash

### ISSUE THREAD

**Issue by markuzzthe1** [OpenEmu/OpenEmu#3929] opened 2019-06-10 00:36 UTC
Summary of issue

https://gyazo.com/ded2876d35e3aaa9b02e19277c494804
Here is the link to the save file i retrieved : https://www.datafilehost.com/d/ba1856f2
Virus Scan : https://gyazo.com/981845c0637178cfed8f9db89a341322

Updated to 2.0.8 and my GBA save files were moved to the trash and now i can't open them because some sort of core is missing?

**Comment by clobber** [comment] 2019-06-10 00:51
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3436

**Closed by clobber** 2019-06-10 00:51 UTC
