### ISSUE TITLE
Newly imported zipped ROMs will not extract before load

### ISSUE THREAD

**Issue by enemyboss** [OpenEmu/OpenEmu#3127] opened 2017-04-06 05:13 UTC
It appears that the SNES9X core was updated today to 1.54.1.  But on my macbook air 2011, it caused all my SNES roms to fail with "emulator could not load ROM".  

 It  works if I provide .sfc (unzipped) SNES roms.  Downloading SNES9x 1.53.5 core plugin fixed the problem and allowed me to load zipped SNES roms again.

**Comment by clobber** [comment] 2017-04-06 05:18
Cannot replicate this here with OpenEmu 2.0.5 (only supported version) and the SNES9x 1.54.1 core plugin. The frontend unzips the ROMs before passing them to the emulator core. It's possible there are some compatibility issues with certain games you are running in the updated plugin, and as you import .sfc (unzipped) they are actually getting run in Higan instead, where they work.

**Comment by enemyboss** [comment] 2017-04-06 06:20
At the moment I don't have the Higan core installed (I checked installed cores in preferences).  I cannot change SNES cores in-game like I would if I had both installed.  

I did a fresh install of OpenEMU (deleted ~/Library/Application Support/OpenEMU)  with only SNES9x core installed and it still failed. If I unzip the ROM and add to library it works.  

Downgrading the core to 1.53.5 allows me to load and import .zip SNES roms, then if I let OpenEMU update the core, the ROMS that were imported as zip will fail to load again.  

I do not doubt that the front-end is responsible for decompressing zipped ROM for the emulator but it looks like the newest core isn't accepting decompressed ROM the front-end passes to it. I also tried re-zipping the .sfc ROM file using the Mac utility but the result is the same. 

Anything else I can try?  I'd like to figure out whats really happening on my system.

**Comment by clobber** [comment] 2017-04-06 06:45
Provide me with an example game. Also the version of macOS/OS X and OpenEmu you are using.

**Comment by enemyboss** [comment] 2017-04-06 08:40
Machine: Macbook Air 13" 2011
OS: macOS Sierra 10.12.4
OpenEMU: V2.05

One example game is Super Castlevania IV, but its happening on all my zipped SNES ROMS.  I've attached a homebrew ROM, which should be safe to distribute and exhibits the same problem.  
[jpr.zip](https://github.com/OpenEmu/OpenEmu/files/901977/jpr.zip)

**Comment by clobber** [comment] 2017-04-06 14:56
It seems that since 2.0.4, newly imported zipped ROMs will not extract before loading. Haven't yet tracked down where this broke or if it is 10.12 SDK related.

**Comment by clobber** [comment] 2017-04-06 16:39
Traced to commit https://github.com/OpenEmu/OpenEmu/commit/be82ff794616bb47c7cb69d2370dbd0cb50bf307

**Comment by clobber** [comment] 2017-04-07 06:42
The root cause is fixed in https://github.com/OpenEmu/OpenEmu/commit/dbc6b5a2c5fc8d50fe08d0d2f2d1ffc097569a02

Since zipped ROMs were being incorrectly imported, you will want to delete any currently imported "zipped" ROMs from your library (because they are not actually zipped!), and then redownload and reimport them. Especially so for SNES games.

The issue there was the SNES9x core update was revealing the import of zipped ROMs being broken in the first place. The previous core version had an implementation bug that would never fully pass back the file extension and so SNES9x could never catch `if (strcasecmp(ext, "zip") == 0)`. So there were two issues going on and one wasn't easily known without the other.

Anyway, do all this after the 2.0.6 update which will probably be available this weekend.

**Closed by clobber** 2017-04-07 06:42 UTC
Labels: Import, ⚑ Bug

**Comment by clobber** [comment] 2017-04-09 05:35
I've mitigated this with a SNES9x 1.54.1.1 core update. It will now load any ROM, despite file extension, even though a bug in OpenEmu 2.0.4 was mucking things up for importing zipped ROMs.
