### ISSUE TITLE
Certain key bindings change after restart with pokken tournament controller

### ISSUE THREAD

**Issue by ChikyuKaze** [OpenEmu/OpenEmu#2562] opened 2016-05-23 03:36 UTC
After binding the controller's up, down, left, right on any system, turning off openemu and turning it back on, up becomes "west", down becomes "east",  left becomes "south", and right becomes "north"
its become an annoyance defaulting the key bindings back to where they were each time, is this my controller or is there something wrong the pokken tournament controllers in general?

**Comment by clobber** [comment] 2016-05-23 03:53
Please search before opening a new issue, dupe of #2395

Will be fixed for next release.

**Closed by clobber** 2016-05-23 03:53 UTC
