### ISSUE TITLE
SNES lag/stutter MBP 13" mid-2018 MacOS Mojave 10.14.1

### ISSUE THREAD

**Issue by pocket2s** [OpenEmu/OpenEmu#3783] opened 2018-11-07 06:46 UTC
I'm getting a lot of lag/stutter on the SNES emulator on my newly purchased 13" mid-2018 MBP. One of the first things I installed on this machine was OpenEmu.

I've tried Super Mario World and it started off at what seems to be a smooth 60 fps, but then a few seconds into the game it goes way below that. I've tried all the least demanding filters including nearest neighbor. I've tried lowering the desktop resolution before loading OpenEmu and I have also tried low-res mode from the Get Info option from Finder but the same issue persists. 

Non-emulated 2d games such as Rayman Origins work fine, even at the highest resolution this computer has to offer. OpenEMu games used to work fine on my 13" Early-2015 MBP with any filter. Could this be Mojave related, throttle related, or Touch Bar related? I have noticed that if I use the Touch Bar during Rayman Origins, to change the volume for example, the entire game stutters until I am done touching the bar to set the volume. 

[Spindump.txt](https://github.com/OpenEmu/OpenEmu/files/2556301/Spindump.txt)

**Comment by clobber** [comment] 2018-11-07 06:53
>Could this be Mojave related, throttle related, or Touch Bar related?

Probably none of the above. I'd wager Intel GPU driver bug, but since you don't have a discrete GPU we cannot test that theory.

**Comment by pocket2s** [comment] 2018-11-09 19:05
Since I was within the 14-day grace period of purchasing this computer, I was able to swap it out for a brand-new one. The problem is still the same. Can't even run an almost 30 year old game on a system that costs nearly $2,000! Do you think they would fix this bug?

**Comment by clobber** [comment] 2018-11-09 19:15
The age of a game and cost of the machine is irrelevant and you should not make the mistake of thinking that matters. The problem is likely at the render level, so in this case OpenGL. Intel drivers are known to be sub-par on macOS, but your problem could possibly go away if we used a Metal renderer for 2D games (quite a bit of work and not happening soon). This is just speculation though, as I don't have an Intel Iris Plus Graphics 640/655 to test with. As for the problem being resolved in a macOS update: unlikely, now that OpenGL is deprecated in 10.14.

**Comment by clobber** [comment] 2018-11-24 20:06
A dev team member with the Mid 2018 MacBook Pro with Touch Bar (Intel Iris Plus Graphics 655, 2.3GHz Intel Core i5 processor) -- which sounds like the same model as yours, cannot replicate this problem. Short of having your particular machine on a desk in front of us, we probably can't investigate further.

**Closed by clobber** 2018-11-24 20:06 UTC
Labels: invalid
