### ISSUE TITLE
Keyboard input doesn't work at all (nor does the edit controls preference page)

### ISSUE THREAD

**Issue by jakeparis** [OpenEmu/OpenEmu#2394] opened 2016-02-01 00:57 UTC
Using version 2.0.1 on El Capitan. no game or game system receives any input. The edit controller page cannot be edited for any game system.

**Comment by clobber** [comment] 2016-02-01 05:51
This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-02-01 05:51 UTC
