### ISSUE TITLE
RetroPort controller mapping glitchy

### ISSUE THREAD

**Issue by pixeltarian** [OpenEmu/OpenEmu#1006] opened 2014-01-06 04:48 UTC
http://cl.ly/image/0s0n2y2F3D1S

There is a gif of me trying to map my SNES controller which is plugged into a retroport usb. 

I am pressing the corresponding control on the snes controller. When it skips a field it's happening when I press the control. I am not doing anything other than pressing the corresponding controllers on the snes controller. so far it's impossible to map.

**Comment by S1ayer** [comment] 2016-01-09 19:01
Hello.

I currently bought the Logitech F710 Controller and I have exactly the same problem as described above.   As mentioned I deleted the "Default.oebindings" file and tried it again but I didn't succeed.

For me it is happening when mapping the Game Boy controls for A and B. What I want to do is to assign (just to have the similar button alignment as on the Game Boy):
- B on F710 to button A
- A on F710 to button B

But when I press the according button on my controller, he jumps one field more and adds the value there. There seems to be partial workaround: Just go to the field before and assign the button there. Partial because then the button B (of Game Boy) doesn't work as expected (running if key stays pressed). Another workaround is to just use different buttons on the F710 controller like the X and Y. This works.

For info: I'm using the OpenEmu release v2.0.1 (407-g415a4a6-Release).

Thanks for your help.

**Comment by bergmayer** [comment] 2016-01-23 19:01
I'm having the same or a very similar issue with a SNES Retropad.  Physical buttons A and B are both seen as "Button 2."  This controller worked in earlier versions, and other apps right now (e.g. "Controllers Lite") can see that the two buttons are different.

**Comment by NeoTeo** [comment] 2016-01-27 20:26
I also have this issue with OpenEMU 2.0.1 and a SNES RetroPort connected to an actual SNES gamepad.

**Comment by nmclaren** [comment] 2018-02-05 17:05
Confirmed that this remains an issue with the SNES RetroPort in v2.0.6.1

**Comment by clobber** [comment] 2020-01-25 19:02
Officially fixed in OpenEmu 2.2.1, available now.

**Closed by clobber** 2020-01-25 19:02 UTC
Labels: Input
