### ISSUE TITLE
Unable to set second player's controls settings

### ISSUE THREAD

**Issue by emersonthis** [OpenEmu/OpenEmu#1861] opened 2015-03-10 23:52 UTC
When playing a two player game, the custom game controls settings are lost whenever there is a change between player 1 and player1.

OpenEmu v1.0.4
ROM: Super Mario Brothers

**Comment by clobber** [comment] 2015-03-11 00:16
You need to better describe exactly what you are doing and experiencing, step by step. There is probably a misunderstanding with how multiple controllers and binds are set.

**Comment by s-d-p** [comment] 2015-03-11 00:28
Steps to reproduce:

1. Turn on OpenEmu and start Super Mario Brothers
2. Choose 2 Players
3. Player 1 starts and opens "Edit game controls"
4. Player 1 assigns game controls
5. Player 1 dies so it's time for player 2
6. Player 2 repeats steps 3-5 above
7. Player 1's turn again... 
**PROBLEM:** none of the custom game controls settings remain. Most are blank

**Comment by clobber** [comment] 2015-03-11 05:19
This is kind of lacking detail still - you haven't told me how you are assigning game controls per-player.

**Comment by s-d-p** [comment] 2015-03-11 11:17
It seems to happen with any settings, but we usually do...

Up = w
Left = a
Down = s
Right = d
A = k
B = l

Start = return
Select = shift

**Comment by s-d-p** [comment] 2015-03-22 00:15
Update. I tested with USB controller and the same issue happens. The second player's controller buttons are all empty, and then when I enter them and save, they all disappear and become empty again. So player two can never move.

**Comment by s-d-p** [comment] 2015-03-22 00:19
I just had an idea... is it a problem that I'm using the same controller for both first and second player? Does the emulator expect me to have two different USB controllers plugged in at the same time in order for two player games to work normally?

**Comment by clobber** [comment] 2015-03-26 23:59
Hrm yeah, could be an issue with duplicate devices; we'll look into it. Which controllers are you using?

**Comment by s-d-p** [comment] 2015-03-27 00:24
First it was the keyboard. Now a generic USB controller for NES. I can kind of make it work by swapping the USB port between players... And THEN resetting the controls. I think this supports out theory.

**Comment by oivivio** [comment] 2015-03-30 16:39
I too am having a problem mapping my second player SNES controls.  Currently using a Retrode 2 with two SNES controllers and OpenEmu version 1.0.4.  Player 1 is mapped fine, but Player 2 has no control.  When I begin to map the Player 2's controller in OpenEmu's settings, it automatically defaults back to Player 1 in the controller settings and will not allow Player 2 to be mapped.  I've swapped the controllers and Player 1 still works, so not a controller issue.  I just seems like OpenEmu is viewing Retrode as one controller and does not allow the input of both SNES controllers.  

Is anyone else having an issue mapping Player 2 with Retrode or without?  Thanks.

**Comment by clobber** [comment] 2015-11-29 19:52
Okay, so input handling code has been refactored and I was reminded to take a look at this again.

First off, your initial issue with multiple keyboards is expected behavior and won't be fixed.

The issue with duplicate gamepads, however, is something we can resolve but we need more information:

With your USB gamepad device plugged in, run this app http://cl.ly/2K1K400t0H3p

Select your gamepad from the list and then go to File > Export Device Properties and then give us the plist it generates, by uploading to cloudapp, dropbox, transfer.sh, etc.

**Comment by clobber** [comment] 2015-12-28 19:24
After closer reading, it sounded like you were trying to use the *same device* for both Player 1 and Player 2 -- definitely not supported. If this is not the case, feel free to clarify but closing this since we already have issues opened for advanced input configuration options.

**Closed by clobber** 2015-12-28 19:24 UTC
Labels: Input

**Comment by EduardoIbarra** [comment] 2017-04-06 21:38
Hello, I have a similar issue. I'm trying to play Super Mario World  and configure a Sony Dual Shock 4 AND a keyboard  but I can't find how to set the controller for the P1 and the keyboard for the P2 (or viceversa). Sometimes only one of those two inputs work, sometimes the y both work, but they control the same player.
Sometimes, all the input I enter, gets erased once I tried to enter input for another player (from the Controls Settings).

**Comment by reVosugarkane** [comment] 2019-04-11 07:34
I am having a similar issue running OpenEmu with two PS3 bluetooth controllers, the first controller works fine, but the second wont work. The keyboard also keeps deleting the controller settings, in a similar fashion as has been described. On a Mac, for some reason I can't post the plists, but i have them.

**Comment by adnelson** [comment] 2020-11-30 00:18
Also having this issue.

1. Go to Player 1's input controls
1. Choose "Keyboard"
1. Go to Player 2's controls
1. Choose a USB controller (in my case, some wireless imitation SNES controller called "Pro Controller")
1. Go back to Player 1's input controls; they have been wiped out


Also worth mentioning that if I leave player 2 using the keyboard input and I try to assign keys, it doesn't recognize any keyboard input. :(
