### ISSUE TITLE
PS4 Pad. Regression issue on 2.1.0 / 2.1.1. Reproducible

### ISSUE THREAD

**Issue by Triloworld** [OpenEmu/OpenEmu#4044] opened 2019-11-23 21:47 UTC
There is regression error. 
After upgrade from 2.0.9.1 to 2.1.1 my PS4 Bluetooth controller is lagging. Pressing key is send after period of time. Version 2.1.0 is same problem. I downgrade. I can easily test that situation.
 
# Steps to reproduce

Use version 2.1.0 or 2.1.1.
Connect PS4 Pad by Bluetooth. Mac on cable, Pad recharged fully.
Play Game (i play PS 1 ). Using saved state. About 10min need to be shown (that is crucial, first action is perfect)
I try disconnect between update. I use same options and machine and game. Everything between version is no touch. 
Downgrade to 2.0.9.1 
Issue is gone

# Expected Behavior

Play in 2.1.0 and have no lag after connect.

# Observed Behavior

Pressing key - 2-4 second delay. Even freezing app ;/

# Debugging Information

- Tested on: OpenEmu Version: 2.1.1 / 2.1.0 (wrong working) and 2.0.9.1 (good working)
- macOS Version: 10.15.1 (19B88)

**Comment by clobber** [comment] 2020-01-05 16:59
@Triloworld At the moment we believe this is a 10.15 SDK bug within IOKit. Since you say you can replicate this, please collect a sample of the OpenEmu process. Please run the following command in Terminal.app and then paste the file it generates back here **while you are experiencing this issue with OpenEmu open**.

`sample $(pgrep OpenEmu) > ~/Desktop/oe_sample_results.txt`

Alternatively, you can generate a sample of the **OpenEmu** process from Activity Monitor following this guide: https://support.omnigroup.com/sample-osx/

**Comment by shysaur** [comment] 2020-01-05 18:53
Additionally, please download a test build of OpenEmu from the link below, and try to reproduce the bug. Your problem might be related to issue #4079.

https://send.firefox.com/download/4ea6f60a7d3cdba9/#aXAiYA7S1m_pSrUW0t8U9A

**Comment by Triloworld** [comment] 2020-01-07 12:02
I will provide after i get PS4 pad to my hand. 
After add Sample with my bug, will try @shysaur solution and provide sample with conclusion what's going on. Sorry for delay :)

**Comment by Triloworld** [comment] 2020-01-13 17:54
Actual version used:
[oe_sample_results.txt](https://github.com/OpenEmu/OpenEmu/files/4054912/oe_sample_results.txt)

Version 2.1.1 https://github.com/OpenEmu/OpenEmu/releases/tag/v2.1.1 :
[oe_sample_results.txt](https://github.com/OpenEmu/OpenEmu/files/4054955/oe_sample_results.txt)

**Comment by Triloworld** [comment] 2020-01-13 18:02
Link go down: https://send.firefox.com/download/4ea6f60a7d3cdba9/#aXAiYA7S1m_pSrUW0t8U9A
If you can, pleas re-send it. 

I agree that https://github.com/OpenEmu/OpenEmu/issues/4079 can be same as my. My problem was not 100% CPU as I have more spare resource before that happen. Before, there is going even 10s delay before key was insert to game and cannot stop game by built in UI, just by closing it.

**Comment by clobber** [comment] 2020-01-13 19:38
>Link go down

Download links are temporary. Unhelpful people lurking in these issues are also downloading, so you want to download immediately when we link one to you. This new one will last for 7 days or 20 downloads, which ever comes first:

https://send.firefox.com/download/15b6ff73ccedb67a/#8b9joNmsJdGwdVDqmxIbPg

**Comment by Triloworld** [comment] 2020-01-13 21:52
Yep. That build is proper solution. Everything work fine like in old version ! :)
Is this will be pushed to main repo?

**Comment by clobber** [comment] 2020-01-25 18:58
Officially fixed in OpenEmu 2.2.1, available now.

**Closed by clobber** 2020-01-25 18:58 UTC
Labels: Input, bug
