### ISSUE TITLE
my keyboard wont work with controls at all on my macbook proretina 

### ISSUE THREAD

**Issue by Sesshy89** [OpenEmu/OpenEmu#2639] opened 2016-07-15 09:02 UTC
ive tried closing down the app but it wont let me configure my controls for any emulator. i just really want to play pokemon please help

**Comment by clobber** [comment] 2016-07-15 17:08
Need to use the search.

This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-07-15 17:08 UTC

**Comment by Sesshy89** [comment] 2016-07-15 18:25
I've tried closing everything and still nothing. Is there something else I can do??
