### ISSUE TITLE
(Another feature request) Slowdown and/or speed setting?

### ISSUE THREAD

**Issue by ApertureSO** [OpenEmu/OpenEmu#2949] opened 2016-12-10 19:45 UTC
They are things that many emulators have. Even though I love OpenEmu, I was hoping that there was going to be an emulation speed setting or at least slowdown like many other emulators.
Please implement this. You were able to make fast forward so I don't think it should be too hard to do.

**Comment by clobber** [comment] 2016-12-11 03:40
Hey, just a tip: as a developer, hearing "it shouldn't be too hard" or "another app has X feature" is rather presumptuous and just not helpful. Maybe we have different goals or design choices, or maybe something *is* more complex to implement than you assume. Our software is open source, so one is always free to download and modify the code as they see fit, if they are capable.

That said, this issue is a duplicate of a feature request. Please search before opening a new one. #803

**Closed by clobber** 2016-12-11 03:40 UTC

**Comment by ApertureSO** [comment] 2016-12-14 19:14
I was asking for a speed setting which you would be able to change through either a menu option or binds (For example, 2 buttons, 1 for speeding up by 10%, another for slowing down by 10%) that would change the speed for as long as you wanted. The feature request you were referring to was asking if you could change the speed of fast forwarding with analog triggers. It also didn't mention slowdown. So I don't see how this is a duplicate. I'm sorry if I seem rude to you but I thought you could just use some leftover code and implement it into your software, or reverse a function to create another.
