### ISSUE TITLE
New MacOS beta unsupported.

### ISSUE THREAD

**Issue by jamess5000** [OpenEmu/OpenEmu#3636] opened 2018-06-05 04:26 UTC
Whenever opened, OpenEmu crashes and says to tell the developer. I'm on MacOS 10.4 Mojave beta.

**Comment by clobber** [comment] 2018-06-05 04:33
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Also just a side note, you should not be running macOS betas for general use. We seem to have to repeat this every update cycle.

Duplicate of #3635

**Closed by clobber** 2018-06-05 04:33 UTC
Labels: duplicate
