### ISSUE TITLE
App hangs when trying to change game library folder

### ISSUE THREAD

**Issue by deadkarma** [OpenEmu/OpenEmu#2170] opened 2015-11-25 14:44 UTC
Every time I try to change the game library game folder, the app hangs:
Here's the [stack trace](https://gist.github.com/deadkarma/7ce323e753f2648fd84f)

Additionally, when clicking 'Reset' I get this alert:
![image](https://cloud.githubusercontent.com/assets/196618/11400051/11958172-9359-11e5-8c71-694122e1a544.png)

**Comment by clobber** [comment] 2015-11-25 18:42
Wow we are now getting a new dupe of this daily.

*Please* search before opening a new issue. Fixed for next release.

#2000

**Closed by clobber** 2015-11-25 18:42 UTC

**Comment by deadkarma** [comment] 2015-11-25 18:53
@clobber Hey, thanks for the info.
I did a search and from what I can tell, there are no open issues for this particular bug
