### ISSUE TITLE
PSP Game's Locale didn't Follow the Region Settings in Preference -> Secret Configuration

### ISSUE THREAD

**Issue by jerrypc2036** [OpenEmu/OpenEmu#4489] opened 2021-04-03 13:10 UTC
Summary of issue

Even if the region settings in OpenEmu's Preference -> Secret menu is set to Japan, PSP core still runs in US mode

# Steps to reproduce

Some PSP game's language follows the PSP's language settings, for example, Final Fantasy IV - Complete Collection,
even if the region settings in OpenEmu's Preference -> Secret menu is set to "Janan", game's UI is still in English in Final Fantasy IV.

# Expected Behavior

PSP games that follow the language settings in PSP should run in Japanese mode and use "O" as confirmation key and "X" as cancel key.

# Observed Behavior

Language of Final Fantasy IV - Complete Collection is in English and "X" key is acted as confirmation.

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 11.2.3

**Comment by jerrypc2036** [comment] 2021-04-03 14:05
Providing core's version information,
- PPSSPP core version: 1.10.3.1

**Comment by clobber** [comment] 2021-04-03 16:41
That's not what that option does. It's for changing the UI region (mainly the sidebar) and not for cores.

Duplicate of #1083

**Closed by clobber** 2021-04-03 16:41 UTC
