### ISSUE TITLE
10.11: iBuffalo Classic USB Gamepad unrecognized

### ISSUE THREAD

**Issue by phillipbergner** [OpenEmu/OpenEmu#1966] opened 2015-07-05 01:52 UTC
I have an iMac Retina 5K (2014) desktop computer and the 10.11 El Capitan developer build installed. When my iBuffalo Classic USB Gamepad is plugged in, OpenEmu will crash. The gamepad appears to otherwise work in other applications. It previously worked fine in 10.10 Yosemite on this computer.

I'm happy to dig further to help correct this issue. Below is the crash report:
https://gist.github.com/anonymous/9d5120c6cb5585f1b265

**Comment by clobber** [comment] 2015-07-05 02:58
Try closing the app, navigating to ~/Library/Application Support/OpenEmu and deleting "Bindings Configurations" as well as "Systems" if the folder exists, then reopen the application.

**Comment by phillipbergner** [comment] 2015-07-05 14:06
Thank you for the quick reply. I was able to delete the Bindings Configurations folder. The app will open if the controller isn't attached, but it will still crash as soon as I plug it in.

**Comment by clobber** [comment] 2015-07-05 16:29
Could be a 10.11 beta problem that will work itself out in a future beta release, or a conflict with another device in our automap database. With your gamepad plugged in, run the following command in Terminal and paste the output back here: `system_profiler SPUSBDataType`

**Comment by phillipbergner** [comment] 2015-07-05 22:52
I wouldn't be surprised if it's a beta problem - it's still relatively early in the development cycle. The controller shows as the last device in this output:

USB:

    USB 3.0 Bus:

      Capacity: 2 TB (2,000,398,934,016 bytes)
      Removable Media: Yes
      BSD Name: disk3
      Host Controller Driver: AppleUSBXHCILPTH
      Partition Map Type: GPT (GUID Partition Table)
      PCI Device ID: 0x8c31 
      PCI Revision ID: 0x0005 
      PCI Vendor ID: 0x8086 
      Volumes:
        EFI:
          Capacity: 209.7 MB (209,715,200 bytes)
          BSD Name: disk3s1
          Content: EFI
          Volume UUID: 0E239BC6-F960-3107-89CF-1C97F78BB46B
        disk3s2:
          Capacity: 2 TB (2,000,054,960,128 bytes)
          BSD Name: disk3s2
          Content: Apple_CoreStorage
        Boot OS X:
          Capacity: 134.2 MB (134,217,728 bytes)
          BSD Name: disk3s3
          Content: Apple_Boot
          Volume UUID: E4561BC9-BE7A-32F7-8868-B9C33F3924C1

        USB3.0 Hub             :

          Product ID: 0x0812
          Vendor ID: 0x2109  (VIA Labs, Inc.)
          Version: b.e1
          Speed: Up to 5 Gb/sec
          Manufacturer: VIA Labs, Inc.         
          Location ID: 0x14800000 / 7
          Current Available (mA): 1800
          Current Required (mA): 0
          Extra Operating Current (mA): 0

        BRCM20702 Hub:

          Product ID: 0x4500
          Vendor ID: 0x0a5c  (Broadcom Corp.)
          Version: 1.00
          Speed: Up to 12 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14600000 / 3
          Current Available (mA): 1000
          Current Required (mA): 94
          Extra Operating Current (mA): 0
          Built-In: Yes

            Bluetooth USB Host Controller:

              Product ID: 0x828d
              Vendor ID: 0x05ac  (Apple Inc.)
              Version: 1.08
              Speed: Up to 12 Mb/sec
              Manufacturer: Apple Inc.
              Location ID: 0x14630000 / 10
              Current Available (mA): 1000
              Current Required (mA): 0
              Extra Operating Current (mA): 0
              Built-In: Yes

        FaceTime HD Camera (Built-in):

          Product ID: 0x8511
          Vendor ID: 0x05ac  (Apple Inc.)
          Version: 72.30
          Serial Number: CC2EAP01FRFRQMF0
          Speed: Up to 480 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14500000 / 8
          Current Available (mA): 1000
          Current Required (mA): 500
          Extra Operating Current (mA): 0
          Built-In: Yes

        USB3.0 Device:

          Product ID: 0x0539
          Vendor ID: 0x152d  (JMicron Technology Corp.)
          Version: 1.00
          Serial Number: AA0000000001
          Speed: Up to 480 Mb/sec
          Manufacturer: JMicron
          Location ID: 0x14300000 / 5
          Current Available (mA): 1000
          Current Required (mA): 2
          Extra Operating Current (mA): 0
          Capacity: 2 TB (2,000,398,934,016 bytes)
          Removable Media: Yes
          Detachable Drive: Yes
          BSD Name: disk3
          Partition Map Type: GPT (GUID Partition Table)
          Volumes:
            EFI:
              Capacity: 209.7 MB (209,715,200 bytes)
              BSD Name: disk3s1
              Content: EFI
              Volume UUID: 0E239BC6-F960-3107-89CF-1C97F78BB46B
            disk3s2:
              Capacity: 2 TB (2,000,054,960,128 bytes)
              BSD Name: disk3s2
              Content: Apple_CoreStorage
            Boot OS X:
              Capacity: 134.2 MB (134,217,728 bytes)
              BSD Name: disk3s3
              Content: Apple_Boot
              Volume UUID: E4561BC9-BE7A-32F7-8868-B9C33F3924C1

        Apple USB SuperDrive:

          Product ID: 0x1500
          Vendor ID: 0x05ac  (Apple Inc.)
          Version: 2.03
          Serial Number: KZ7ECIF3929         
          Speed: Up to 480 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14200000 / 4
          Current Available (mA): 1000
          Current Required (mA): 500
          Extra Operating Current (mA): 0

        USB2.0 Hub             :

          Product ID: 0x2812
          Vendor ID: 0x2109  (VIA Labs, Inc.)
          Version: b.e0
          Speed: Up to 480 Mb/sec
          Manufacturer: VIA Labs, Inc.         
          Location ID: 0x14100000 / 2
          Current Available (mA): 1000
          Current Required (mA): 0
          Extra Operating Current (mA): 0

            Composite Device:

              Product ID: 0x2060
              Vendor ID: 0x0583  (Padix Co., Ltd.)
              Version: 1.00
              Speed: Up to 1.5 Mb/sec
              Location ID: 0x14120000 / 16
              Current Available (mA): 1000
              Current Required (mA): 100
              Extra Operating Current (mA): 0

**Comment by clobber** [comment] 2015-07-05 23:17
Oh, you're plugged into a USB Hub. Those are problems for us, usually, so I'd try plugging your device directly into the machine and bypassing any kind of hub.

**Comment by phillipbergner** [comment] 2015-07-05 23:21
Thanks for the suggestion. I just tried plugging directly into the computer - including deleting the Bindings Configurations again before I started, but it still crashes. Maybe I'll wait this one out for the next beta and try again.

**Comment by phillipbergner** [comment] 2015-08-17 00:48
I am now on build 15A244d and I still have the same problem. I can post the latest crash report if you'd find that helpful.

**Comment by dalecoop** [comment] 2015-08-17 11:07
Hi there, 

I have the same crash problem with my MacbookPro 10.11 El Capitan public beta anomy iBuffalo SNES USB controller :(

Hope the problem will be solved soon.
Thanks for your work.

**Comment by satchow** [comment] 2015-08-21 21:50
I have the same problem. Love the controller, unfortunate it doesn't work yet.

**Comment by nameCantBeBlank** [comment] 2015-08-27 19:36
Newest El Capitan Beta (15A262e) and iBuffalo controller, doesn't show in v1.0.4 my retrolink control does.

**Comment by clobber** [comment] 2015-09-14 18:57
@phillipbergner @dalecoop @satchow @nameCantBeBlank @plauclair @bears20151 with your "iBuffalo" device plugged in, run this app http://cl.ly/2K1K400t0H3p

Select your gamepad from the list and then go to File > Export Device Properties and then give us the plist it generates, by uploading to cloudapp, dropbox transfer.sh, etc.

It is important *everyone* does this so we can analyze your device.

**Comment by satchow** [comment] 2015-09-14 20:33
For some reason it won't let me Export Device Properties (as nothing happens when I click it in the menu) but here is a screenshot. Hopefully it helps.

https://gyazo.com/ee16cda6f1a9ea0b19e521910d278ba9

**Comment by clobber** [comment] 2015-09-14 21:41
Okay, your device isn't reporting a Product and Manufacturer string which seems out of spec to me, so not surprised OE isn't picking it up. These generic clone gamepads are always crap.

Is this the same behavior on 10.10 - can someone test? I've already heard this device worked fine on 10.10 so what exactly was the device name appearing in OE's *Control Preferences* for "Input" ?

**Comment by dalecoop** [comment] 2015-09-15 10:35
Like satchow, I tried, with my iBuffalo SNES USB controller plugged, OS X El Capitan GM (10.11), and same result, empty item on list (my controller) and nothing happen when I try to export.

**Comment by clobber** [comment] 2015-09-15 16:48
@dalecoop Thanks. On 10.10 what is the device name appearing in OE's *Control Preferences* for "Input" with your controller plugged in? You can screenshot it if you like.

Also if you are still on 10.10 with your gamepad plugged in, run the following command in Terminal and paste the output back here: `system_profiler SPUSBDataType`

**Comment by clobber** [comment] 2015-09-15 16:51
Also @satchow you being on 10.11, can you do the following:

With your gamepad plugged in, run the following command in Terminal and paste the output back here: `system_profiler SPUSBDataType`

**Comment by satchow** [comment] 2015-09-15 18:36
Here you go.

USB:

    USB 3.0 Bus:

      Capacity: 62.88 GB (62,881,005,568 bytes)
      Removable Media: Yes
      BSD Name: disk2
      Host Controller Driver: AppleUSBXHCILPTH
      Partition Map Type: MBR (Master Boot Record)
      PCI Device ID: 0x8c31 
      PCI Revision ID: 0x0005 
      PCI Vendor ID: 0x8086 
      Volumes:
        NiftyMD:
          Capacity: 62.86 GB (62,864,228,352 bytes)
          Available: 11.18 GB (11,181,096,960 bytes)
          Writable: Yes
          File System: ExFAT
          BSD Name: disk2s1
          Mount Point: /Volumes/NiftyMD
          Content: Windows_NTFS
          Volume UUID: C8BF5026-0077-3F03-AA08-019E0A1DC444

        Card Reader:

          Product ID: 0x8406
          Vendor ID: 0x05ac  (Apple Inc.)
          Version: 8.20
          Serial Number: 000000000820
          Speed: Up to 5 Gb/sec
          Manufacturer: Apple
          Location ID: 0x14700000 / 19
          Current Available (mA): 1800
          Current Required (mA): 224
          Extra Operating Current (mA): 0
          Capacity: 62.88 GB (62,881,005,568 bytes)
          Removable Media: Yes
          Detachable Drive: Yes
          BSD Name: disk2
          Built-In: Yes
          Partition Map Type: MBR (Master Boot Record)
          Volumes:
            NiftyMD:
              Capacity: 62.86 GB (62,864,228,352 bytes)
              Available: 11.18 GB (11,181,096,960 bytes)
              Writable: Yes
              File System: ExFAT
              BSD Name: disk2s1
              Mount Point: /Volumes/NiftyMD
              Content: Windows_NTFS
              Volume UUID: C8BF5026-0077-3F03-AA08-019E0A1DC444

        Apple Internal Keyboard / Trackpad:

          Product ID: 0x0262
          Vendor ID: 0x05ac  (Apple Inc.)
          Version: 2.25
          Speed: Up to 12 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14400000 / 3
          Current Available (mA): 1000
          Current Required (mA): 40
          Extra Operating Current (mA): 0
          Built-In: Yes

        BRCM20702 Hub:

          Product ID: 0x4500
          Vendor ID: 0x0a5c  (Broadcom Corp.)
          Version: 1.00
          Speed: Up to 12 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14300000 / 4
          Current Available (mA): 1000
          Current Required (mA): 94
          Extra Operating Current (mA): 0
          Built-In: Yes

            Bluetooth USB Host Controller:

              Product ID: 0x8289
              Vendor ID: 0x05ac  (Apple Inc.)
              Version: 1.12
              Speed: Up to 12 Mb/sec
              Manufacturer: Apple Inc.
              Location ID: 0x14330000 / 6
              Current Available (mA): 1000
              Current Required (mA): 0
              Extra Operating Current (mA): 0
              Built-In: Yes

        Composite Device:

          Product ID: 0x2060
          Vendor ID: 0x0583  (Padix Co., Ltd.)
          Version: 1.00
          Speed: Up to 1.5 Mb/sec
          Location ID: 0x14100000 / 21
          Current Available (mA): 1000
          Current Required (mA): 100
          Extra Operating Current (mA): 0

**Comment by clobber** [comment] 2015-09-15 20:10
@satchow @dalecoop Another thing I need -

With your device plugged in, open up Console.app and then load OpenEmu. Copy and paste all the output from OpenEmu back here. If OE is still crashing on 10.11 with this device plugged in, also copy and paste the crash log too.

**Comment by satchow** [comment] 2015-09-15 20:16
Console and Crash Report:
http://pastebin.com/EWewtpMS

**Comment by clobber** [comment] 2015-09-15 20:39
Okay, it seems some behavior changed on 10.11 for devices that don't report a USB HID manufacturer and/or product string. Previously it'd return some kind of generic string based on the number of elements, but now on 10.11 it returns `nil`. I'll post a build later with a fix to test.

First I still want to check out the old behavior on **10.10** so @dalecoop could you supply the various info I need: https://github.com/OpenEmu/OpenEmu/issues/1966#issuecomment-140459773 and https://github.com/OpenEmu/OpenEmu/issues/1966#issuecomment-140523351

**Comment by phillipbergner** [comment] 2015-09-15 23:18
@clobber I can confirm I get the same results as @dalecoop where I have an empty list when I run HIDBrowser. Sorry I'm late to the game here. Let me know if you need anything else to help fix this.

**Comment by dalecoop** [comment] 2015-09-16 07:20
Hi there, 
Sorry I couldn't do it before... there it is (with my OS X 10.10.5 Yosemite) :

![screensot 2015-09-16 09 05 46](https://cloud.githubusercontent.com/assets/7123591/9898628/18ab9e88-5c54-11e5-9088-a354f5e074c6.png)
----------------------------------------------------------------------------
OSX 10.10.5 - Console
----------------------------------------------------------------------------
16/09/2015 09:09:06,802 OpenEmu[1621] OELibraryDatabase loadFromURL: 'file:///Users/developpement/Library/Application%20Support/OpenEmu/Game%20Library/'
16/09/2015 09:09:06,949 OpenEmu[1621] Apple Keyboard
16/09/2015 09:09:07,174 OpenEmu[1621] Device is already being handled
16/09/2015 09:09:07,174 OpenEmu[1621] USB,2-axis 8-button gamepad

----------------------------------------------------------------------------
OSX 10.10.5 - system_profiler SPUSBDataType
----------------------------------------------------------------------------
USB:

    USB 3.0 SuperSpeed Bus:

      Host Controller Location: Built-in USB
      Host Controller Driver: AppleUSBXHCI
      PCI Device ID: 0x1e31
      PCI Revision ID: 0x0004
      PCI Vendor ID: 0x8086
      Bus Number: 0x0a

    USB 3.0 Hi-Speed Bus:

      Host Controller Location: Built-in USB
      Host Controller Driver: AppleUSBXHCI
      PCI Device ID: 0x1e31
      PCI Revision ID: 0x0004
      PCI Vendor ID: 0x8086
      Bus Number: 0x0a

        USB,2-axis 8-button gamepad:

          Product ID: 0x2060
          Vendor ID: 0x0583  (Padix Co., Ltd.)
          Version: 1.00
          Speed: Up to 1.5 Mb/sec
          Location ID: 0x14400000 / 5
          Current Available (mA): 500
          Current Required (mA): 100

        USB Optical Mouse:

          Product ID: 0xc05a
          Vendor ID: 0x046d  (Logitech Inc.)
          Version: 63.00
          Speed: Up to 1.5 Mb/sec
          Manufacturer: Logitech
          Location ID: 0x14300000 / 3
          Current Available (mA): 500
          Current Required (mA): 100

    USB Hi-Speed Bus:

      Host Controller Location: Built-in USB
      Host Controller Driver: AppleUSBEHCI
      PCI Device ID: 0x1e26
      PCI Revision ID: 0x0004
      PCI Vendor ID: 0x8086
      Bus Number: 0x1d

        Hub:

          Product ID: 0x0024
          Vendor ID: 0x8087  (Intel Corporation)
          Version: 0.00
          Speed: Up to 480 Mb/sec
          Location ID: 0x1d100000 / 2
          Current Available (mA): 500
          Current Required (mA): 0
          Built-In: Yes

            Hub:

              Product ID: 0x2512
              Vendor ID: 0x0424  (SMSC)
              Version: b.b3
              Speed: Up to 480 Mb/sec
              Location ID: 0x1d180000 / 3
              Current Available (mA): 500
              Current Required (mA): 2
              Built-In: Yes

                BRCM20702 Hub:

                  Product ID: 0x4500
                  Vendor ID: 0x0a5c  (Broadcom Corp.)
                  Version: 1.00
                  Speed: Up to 12 Mb/sec
                  Manufacturer: Apple Inc.
                  Location ID: 0x1d181000 / 5
                  Current Available (mA): 500
                  Current Required (mA): 94
                  Built-In: Yes

                    Bluetooth USB Host Controller:

                      Product ID: 0x828a
                      Vendor ID: 0x05ac  (Apple Inc.)
                      Version: 1.06
                      Speed: Up to 12 Mb/sec
                      Manufacturer: Apple Inc.
                      Location ID: 0x1d181300 / 7
                      Current Available (mA): 500
                      Current Required (mA): 0
                      Built-In: Yes

                IR Receiver:

                  Product ID: 0x8242
                  Vendor ID: 0x05ac  (Apple Inc.)
                  Version: 1.00
                  Speed: Up to 1.5 Mb/sec
                  Manufacturer: Apple, Inc.
                  Location ID: 0x1d182000 / 4
                  Current Available (mA): 500
                  Current Required (mA): 100
                  Built-In: Yes

    USB Hi-Speed Bus:

      Host Controller Location: Built-in USB
      Host Controller Driver: AppleUSBEHCI
      PCI Device ID: 0x1e2d
      PCI Revision ID: 0x0004
      PCI Vendor ID: 0x8086
      Bus Number: 0x1a

        Hub:

          Product ID: 0x0024
          Vendor ID: 0x8087  (Intel Corporation)
          Version: 0.00
          Speed: Up to 480 Mb/sec
          Location ID: 0x1a100000 / 2
          Current Available (mA): 500
          Current Required (mA): 0
          Built-In: Yes

            Keyboard Hub:

              Product ID: 0x1006
              Vendor ID: 0x05ac  (Apple Inc.)
              Version: 96.15
              Serial Number: 000000000000
              Speed: Up to 480 Mb/sec
              Manufacturer: Apple, Inc.
              Location ID: 0x1a120000 / 3
              Current Available (mA): 500
              Current Required (mA): 300

                Apple Keyboard:

                  Product ID: 0x0250
                  Vendor ID: 0x05ac  (Apple Inc.)
                  Version: 0.74
                  Speed: Up to 1.5 Mb/sec
                  Manufacturer: Apple Inc.
                  Location ID: 0x1a122000 / 4
                  Current Available (mA): 100
                  Current Required (mA): 20

**Comment by clobber** [comment] 2015-09-16 07:24
Thanks, got it. It actually looks like an IOKit bug on 10.11 with this device so I've opened a ticket with Apple.

**Comment by clobber** [comment] 2015-09-16 23:07
Okay, heard back from Apple. More information is required to diagnose the problem, so those on **10.11 with your device plugged in**, please do the following to obtain a full System Information Report:
>
1. Select About This Mac from the Apple Menu
2. Click the System Report button on the About This Mac window
3. Select Save from the File menu (cmd-s)
4. Change the file name and save location as needed
5. Click the Save button
>
This report can also be obtained in Terminal using the following command:
>
/usr/sbin/system_profiler -detailLevel full -xml > ~/Desktop/mymachine.spx


Once you have the report file, upload it to cloudapp, dropbox, google drive, transfer.sh, etc and link it back here.

**Comment by satchow** [comment] 2015-09-16 23:20
Here you go
https://www.dropbox.com/s/ky5h6urgcwz1r9t/MacBook%20Pro.spx?dl=0

**Comment by phillipbergner** [comment] 2015-09-17 11:12
https://drive.google.com/file/d/0BypfAV0zO-58Vm9tdmkySEZFaDQ/view?usp=sharing

**Comment by vBoogs** [comment] 2015-09-17 16:09
https://www.dropbox.com/s/ciqhm5glggcqld2/vBoogs%20MBP%20-%20El%20Capitan.spx?dl=0

**Comment by vBoogs** [comment] 2015-09-25 02:00
Any word from Apple yet clobber? I see they seeded a 10.11.1 beta but I haven't done it yet to see if it resolves the issue. Anyone?

**Comment by plauclair** [comment] 2015-09-25 02:29
Can confirm it did not fix the issue.

**Comment by clobber** [comment] 2015-09-28 03:10
The update from the issue I reported was:
> Engineering has determined that your bug report is a duplicate of another issue and will be closed. 

Sorry, that's all the information that was provided. But since they were able to determine that the problem matched other reported bugs, it will certainly be fixed but don't expect it to be patched in 10.11.1 (as some of you have already checked) since that beta is already out and in-testing for issues patched before that point release cycle started. So my best guess would be for 10.11.2.

Meanwhile, we can provide a workaround on our end that will be available in the next release of OpenEmu.

**Comment by plauclair** [comment] 2015-09-30 23:45
The issue is still there on the latest stable release of El Capitan just released today unfortunately.

**Comment by clobber** [comment] 2015-09-30 23:52
@plauclair I already said you won't see the fix until 10.11.2, most likely.

**Comment by plauclair** [comment] 2015-10-01 00:02
@clobber yep, I got that. I was just posting an update since I didn't know if the latest dev beta and the stable build had any difference in that regard. I would have been very surprised if it would have been so quick, but one can still hope can he? 😉

**Comment by Orestisc** [comment] 2015-10-01 23:05
Well.. barnacles. I just updated to El Capitan and have the same issues, had I known it I wouldn't have updated.
Thanks for the information clobber, I'm looking forward to an update with a workaround solution for OpenEmu.

**Comment by getbuff** [comment] 2015-10-02 20:39
I'm getting the same issue with the final consumer release of El Capitan. Any solutions?

**Comment by clobber** [comment] 2015-10-02 20:49
@getbuff The solution is to actually read this thread instead of needlessly posting in it.

**Comment by brechtm** [comment] 2015-10-05 19:43
Sigh. El Capitan isn't making me happy so far. This is yet another thing it breaks for me...
Anyway, as a temporary solution you can use [Enjoyable](https://yukkurigames.com/enjoyable/) (or equivalent) to use the gamepad with OpenEmu. Simply map the keyboard keys configured in OpenEmu to the gamepad's buttons.

**Closed** 2015-10-06 02:54 UTC
Labels: Input

**Comment by peshi** [comment] 2015-10-06 13:56
Thank you very much for this fix, most appreciated.

**Comment by vBoogs** [comment] 2015-10-07 06:43
I'm a bit of a n00b when it comes to this adding lines thing. I opened up the referenced OpenEmuSystem/OEControllerDescription.m file in Xcode and copied and pasted the fixed code and then saved. Trying the controller in OpenEmu afterwards yields no success. What am I missing? Do I need to "commit" something? I see something like looks like an md5 hash at the top... but I'm not sure if I need it.

Please help this poor, confused gamer!

**Comment by peshi** [comment] 2015-10-07 12:26
@vBoogs You have to clone the repo and compile from source, you can find out how to do it in the wiki.

**Comment by duanefields** [comment] 2015-10-08 01:52
This is working for me with Atari games, but not on the NES or SNES, either core - anybody else get it working on those platforms?

**Comment by duanefields** [comment] 2015-10-08 01:54
I should add that you can setup the controls just fine - they just don't work in the game - or at least the start button doesn't ;-)

**Comment by clobber** [comment] 2015-10-08 05:47
@duanefields Try:

1) Navigate to the folder `~/Library/Application Support/OpenEmu` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)

2) Delete the "Systems" folder (if it exists)

3) Delete Default.oebindings in the "Bindings Configurations" folder.

Reopen app.

**Comment by brechtm** [comment] 2015-10-08 20:53
For me it's working fine with the Nestopia and SNES9x cores at least.

**Comment by cityquartz** [comment] 2015-11-09 04:06
This is my first ever post to Github so please forgive me if I am posting in the incorrect format: I am experiencing this issue with El Capitan 10.11.1 Beta and OpenEmu Experimental 1.04 554-f588330 and the Buffalo SNES USB controller (i.e. OpenEmu > Preferences > Controls > Input the USB controller doesn't appear). 

Does the experimental build include all the latest commits, or do I need to clone the repo and compile it myself? (I've never done this but per a post above there are instructions in the Wiki).

**Comment by plauclair** [comment] 2015-11-09 22:35
@cityquartz you'll have to compile it yourself for now.

**Comment by shaneambers** [comment] 2015-11-27 02:09
why was this closed with no resolution ? ....
