### ISSUE TITLE
[Feature Request] tagging / sorting system for roms or folders

### ISSUE THREAD

**Issue by willemrosenthal** [OpenEmu/OpenEmu#3902] opened 2019-04-15 13:49 UTC
It would be fantastic to be able to either tag roms, then sort them: (I.E. "beat em ups", "shumps", etc) or to be able to group them in folders within each of their systems.

**Comment by clobber** [comment] 2019-04-15 15:21
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

You can also create your own collections in the sidebar.

Duplicate of #2087

**Closed by clobber** 2019-04-15 15:21 UTC
