### ISSUE TITLE
Some N64 Games Permanently in FastForward-like state

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2234] opened 2015-12-25 07:47 UTC
I'm running the most recent version of OpenEmu and Paper Mario seems to be running at an almost unplayable speed.  Anyone else have this problem?  Its only for Paper Mario for some reason.

**Comment by clobber** [comment] 2015-12-25 08:25
Yep, we'll look into it. Please list any other games you find with the problem.

**Comment by clobber** [comment] 2015-12-25 17:20
Incomplete list of games with this problem:
* Banjo-Kazooie
* Banjo-Tooie
* Goldeneye (in-game, not title screens. Note: CPU hits 100%)
* Paper Mario

This seems to be a core implementation problem.

**Comment by hullstar242** [comment] 2015-12-25 17:35
Mario Kart seems a bit off too I'm not sure if its just me though, check it out for yourself.

**Comment by clobber** [comment] 2015-12-25 17:37
Looks fine in-game here.

**Comment by spamguy** [comment] 2015-12-25 21:57
Can verify Banjo-Kazooie runs at about 2x speed. I am running an experimental build from code pulled this morning.

**Comment by Carson-Shook** [comment] 2015-12-27 07:49
Can also verify Banjo-Kazooie is running in double speed. Seems to run normally for about a second after pausing and resuming emulation.

**Comment by sxflynn** [comment] 2015-12-27 23:21
Star Wars Shadows of the Empire runs at a 2x speed. Thank you everyone for all your hard work on this, we appreciate it. Happy Holidays!

**Comment by Mr-Poopy-Butthole** [comment] 2015-12-28 02:15
Goldeneye and Mario Kart are running at a 2x - 3x speed for me. Thank you for the help!

**Comment by commscheck** [comment] 2015-12-29 01:00
Same issue with Banjo Kazooie. Was working fine in v1.0.4. Issue introduced when updating to v2.0.1.

**Comment by clobber** [comment] 2015-12-29 01:10
All: Thanks, appreciate it, but we don't need multiple "me-too" posts telling us Banjo Kazooie has a problem...we get it :)

**Comment by kreeger** [comment] 2015-12-30 17:24
Never could get into _Banjo Kazooie_ so I won't vouch for it, but I _will_ add a list of other games having this issue. I'm running off of a release build (let me know if I need to run based off the latest git repo, I'm happy to do so). Retina MacBook Pro, Mid-2014, GeForce GT 750M.

- 1080º Snowboarding (both in-game and in-menu)
- Batman Beyond: Return of the Joker (in-game only, not menu)

I've been able to verify several games that _don't_ have this issue, so I'm not sure what's up. I'm willing to bet it's an issue with the emulation core.

**Comment by CSindony** [comment] 2016-01-01 20:13
I'm having the 2x speed issue with Banjo-Kazooie. With Banjo-Tooie I'm having a constant lagging issue in a lot of areas of the games, same with Paper Mario.

**Comment by clobber** [comment] 2016-01-03 00:53
@CSindony Please stop posting in unrelated issues. We have already identified there is a problem specific to our core port of Mupen64Plus and N64 games.

**Comment by shanewht** [comment] 2016-01-03 05:53
Extreme G also is at 2x speed. Didn't see that game listed. Not sure if that matters....

**Comment by CSindony** [comment] 2016-01-03 08:49
@clobber Sure. Sorry. Deleted the comment already. Thanks for reading, though.

**Comment by hullstar242** [comment] 2016-01-03 16:06
Is there some sort of slow motion AR or Gameshark code I can use fix this problem temporarily?

**Comment by mrvacbob** [comment] 2016-01-03 21:35
There's something wrong with the multithreaded video timing in OEOpenGL2GameRenderer - seems like a semaphore is not consumed when expected. So the game is allowed to run without FPS limit.

Using glClientWaitSync is what we really want, but it's expensive. Might need to do something like condition variables.

**Comment by mrvacbob** [comment] 2016-01-03 22:46
Removing the dispatch signal in setupAlternateRenderingThread helps but breaks experimental cores.
Also, Paper Mario calls swapBuffers every 2 frames, but our video timing expects every 1 frame.

May be best to do audio-based timing.

**Comment by mrvacbob** [comment] 2016-01-03 23:07
So, the problem is the game is actually 30 fps, but we run it like it was 60 fps.

**Comment by CSindony** [comment] 2016-01-03 23:18
So, @mrvacbob , I guess that this issue will need a 2.0.2 version fix? Or is it something that would need more time to solve for the developers?

**Comment by landryx** [comment] 2016-01-17 04:00
working for the next update? (can't wait to replay bk :P)

**Comment by utd1878** [comment] 2016-02-07 19:49
What are the chances this will be fixed in the next release?  I'm experiencing the same thing.

BTW, this is a great app.  Really impressed.

**Comment by landryx** [comment] 2016-02-07 21:17
it's already been fixed ;)

**Comment by hullstar242** [comment] 2016-02-07 21:39
When will it be released?  Thank you so much :)

**Comment by landryx** [comment] 2016-02-07 21:48
we dont know, soon maybe.

**Comment by SoaringHawk820** [comment] 2016-02-19 01:21
Mario Party 1 is having the problem as well. It's still not fixed

**Comment by landryx** [comment] 2016-02-19 21:20
you must wait an update but it's already been fixed if you compile the new build yourself from the Github. I'm playing Banjo-Kazooie right now ;)

**Comment by hullstar242** [comment] 2016-02-19 21:29
Excuse my ignorance, but how do i compile the new build myself?  Can you post like step by step instructions or like a link to instructions? :(

**Comment by SoaringHawk820** [comment] 2016-02-19 22:01
I'm wondering the same thing

**Comment by landryx** [comment] 2016-02-19 22:17
it's alright, here you are.
https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide

**Comment by hullstar242** [comment] 2016-02-20 06:15
If I'm running the most recent experimental version but I want to compile the updated build myself, do I need clean up my previous version like it says in the instruction?  I have version 2.0.1 

Also if I follow the instructions I'll for sure get the newest version?

**Comment by clobber** [comment] 2016-07-02 01:32
This is fixed in OpenEmu 2.0.2

**Closed by clobber** 2016-07-02 01:32 UTC
Labels: 2.0, Core, ⚑ Bug
