### ISSUE TITLE
Catalina + Adaptoid N64 controller failure

### ISSUE THREAD

**Issue by joeauty** [OpenEmu/OpenEmu#3994] opened 2019-10-18 20:56 UTC
Hello, 

Upon upgrading to Catalina my controller is no longer working. When I launch the app via the Terminal executable so I can see stdout/stderr output when I try to map my controller buttons I'm seeing errors like the following:

*** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], /Users/clobber/Code/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemBindings.m:671

I'm not sure why this path is being display as /Users/clobber, this is not my home directory.

I've enabled Openemu input in my security & privacy pane:

![image](https://user-images.githubusercontent.com/370097/67127857-2e0f0400-f1c8-11e9-9ebe-5df8532aff61.png)

Would any other details be useful here, or is this a known issue?

**Comment by joeauty** [comment] 2019-10-19 02:28
Some more info here... I still have a Mac I haven't upgraded to Catalina yet, it works fine. I've tried compiling manually and deleting all preferences (as well as running `defaults delete org.openemu.OpenEmu`) and no matter what I do the N64 Adaptoid is detected here, but the autosetting doesn't work, and when I manually go map an input my input is not recognized:

![image](https://user-images.githubusercontent.com/370097/67136609-91178f80-f1f6-11e9-82be-a137afdf3c17.png)

**Comment by shysaur** [comment] 2019-10-19 13:15
As a first step, follow the input troubleshooting guide, just to verify that you are not using any software known to cause issues: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

If the input troubleshooting guide did not help, please follow these instructions:

1. Launch OpenEmu via Terminal.app, reproduce the issue, close OpenEmu, and copy+paste the entire contents of the Terminal window into a new text file. Then, post the text file here.
2. Both on the mac with Catalina and on the mac which you have not upgraded, download this app: [HIDBrowser.app.zip](https://github.com/OpenEmu/OpenEmu/files/3746691/HIDBrowser.app.zip). Connect the controller, open HIDBrowser.app (via right-clicking if necessary), and then select "N64 Adaptoid" from the "Device" list. Finally, select "Export Device Properties..." from the File menu, and post the .plist files you have exported.

**Comment by joeauty** [comment] 2019-10-19 15:08
Thanks Shysaur!

I looked at the input troubleshooting guide, and the only app I had running in that list was the Terminal so I tried without the Terminal active and had the same problem. The Terminal worked fine pre-Catalina FYI, my Terminal is almost always open. I also have a USB-C adapter I use for my Adaptoid -> USB C port, and that same one was working pre-Catalina. 

Here is my Terminal stdout as requested for step #1:

```
% /Applications/OpenEmu.app/Contents/MacOS/OpenEmu ; exit;
objc[9292]: Class IKCGRenderer is implemented in both /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit (0x7fff9175bf38) and /Applications/OpenEmu.app/Contents/MacOS/OpenEmu (0x10c1751e8). One of the two will be used. Which one is undefined.
2019-10-19 11:02:55.913 OpenEmu[9292:227603] OELibraryDatabase loadFromURL: 'file:///Users/joeauty/Library/Application%20Support/OpenEmu/Game%20Library/'
CoreData: annotation:  Failed to load optimized model at path '/Applications/OpenEmu.app/Contents/Resources/OEDatabase.momd/OEDatabase 1.3.omo'
2019-10-19 11:02:56.355 OpenEmu[9292:227603] window did load
2019-10-19 11:02:56.360 OpenEmu[9292:227603] Device 0x7fdbe35c9700 does not have a location ID
2019-10-19 11:02:56.360 OpenEmu[9292:227603] Device 0x7fdbe35c9700 does not have a product name.
2019-10-19 11:02:56.361 OpenEmu[9292:227603] Found Device 0x7fdbe35c9700: Touchbar (probably)
2019-10-19 11:02:56.370 OpenEmu[9292:227603] Found Device 0x7fdbe8f3e060: Apple Internal Keyboard / Trackpad
2019-10-19 11:02:56.521 OpenEmu[9292:227603] Device <IOHIDDevice 0x7fdbe35c9700 [0x7fff900b7b00]  'ClassName=IOHIDUserDevice' VendorID=1452 ProductID=34304 PrimaryUsagePage=1 PrimaryUsage=6 ReportInterval=8000> is already being handled
2019-10-19 11:02:56.521 OpenEmu[9292:227603] Found Device 0x7fdbe35afe50: Adaptoid
2019-10-19 11:02:56.524 OpenEmu[9292:227603] Could not find element for control of type: Axis, cookie: 17, usage: X
2019-10-19 11:02:56.524 OpenEmu[9292:227603] Could not find element for control of type: Axis, cookie: 18, usage: Y
2019-10-19 11:02:56.525 OpenEmu[9292:227603] WARNING: There are 2 generic desktop elements unaccounted for in (null)
2019-10-19 11:02:56.525 OpenEmu[9292:227603] Device <IOHIDDevice 0x7fdbe8f3e060 [0x7fff900b7b00]  'ClassName=AppleUserUSBHostHIDDevice' Transport=USB VendorID=1452 ProductID=636 Manufacturer=Apple Inc. Product=Apple Internal Keyboard / Trackpad PrimaryUsagePage=1 PrimaryUsage=6 ReportInterval=0> is already being handled
2019-10-19 11:03:00.687 OpenEmu[9292:227603] Failed to set (menuStyle) user defined inspected property on (OEPopUpButton): [<OEPopUpButton 0x7fdbea294160> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key menuStyle.
2019-10-19 11:03:00.687 OpenEmu[9292:227603] Failed to set (menuStyle) user defined inspected property on (OEPopUpButton): [<OEPopUpButton 0x7fdbea299950> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key menuStyle.
2019-10-19 11:03:00.687 OpenEmu[9292:227603] Failed to set (menuStyle) user defined inspected property on (OEPopUpButton): [<OEPopUpButton 0x7fdbea295050> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key menuStyle.
2019-10-19 11:03:00.693 OpenEmu[9292:227603] Unknown control value for identifier: 'OEControllerAdaptoidN64AnalogLeft' associated with key name: 'OEPSXLeftAnalogLeft'
2019-10-19 11:03:00.693 OpenEmu[9292:227603] Failed to parse default bindings for <OEControllerDescription: 0x7fdbe484c720>!
2019-10-19 11:03:00.694 OpenEmu[9292:227603] Unknown control value for identifier: 'OEControllerAdaptoidN64AnalogUp' associated with key name: 'OEPSPAnalogUp'
2019-10-19 11:03:00.694 OpenEmu[9292:227603] Failed to parse default bindings for <OEControllerDescription: 0x7fdbe484c720>!
2019-10-19 11:03:00.695 OpenEmu[9292:227603] Unknown control value for identifier: 'OEControllerAdaptoidN64AnalogUp' associated with key name: 'OEN64AnalogUp'
2019-10-19 11:03:00.695 OpenEmu[9292:227603] Failed to parse default bindings for <OEControllerDescription: 0x7fdbe484c720>!
2019-10-19 11:03:00.695 OpenEmu[9292:227603] Unknown control value for identifier: 'OEControllerAdaptoidN64AnalogUp' associated with key name: 'OESaturnLeftAnalogUp'
2019-10-19 11:03:00.695 OpenEmu[9292:227603] Failed to parse default bindings for <OEControllerDescription: 0x7fdbe484c720>!
2019-10-19 11:03:09.514 OpenEmu[9292:227603] *** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], /Users/clobber/Code/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemBindings.m:671
2019-10-19 11:03:11.050 OpenEmu[9292:227603] *** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], /Users/clobber/Code/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemBindings.m:671
```

and attached is my Adaptoid plist file from the HIDBrowser output.

[Adaptoid.plist.zip](https://github.com/OpenEmu/OpenEmu/files/3746834/Adaptoid.plist.zip)



If it makes a difference, I've reproduced this problem with both a manually compiled version of OpenEmu as well as the "experimental" build provided on the homepage.

Thanks in advance for your help here!

**Comment by joeauty** [comment] 2019-10-19 15:36
My Mojave HIDBrowser export

[Adaptoid Mojave.plist.zip](https://github.com/OpenEmu/OpenEmu/files/3746855/Adaptoid.Mojave.plist.zip)

**Comment by shysaur** [comment] 2019-10-19 16:50
Thanks! I think I know what is going on. From the logs, it seems that it is just the analog stick which is causing issues. Are you able to map the other buttons on the controller, apart from the analog stick?

Do not touch the analog stick before you attempt to map the other buttons.

**Comment by joeauty** [comment] 2019-10-19 16:59
> Thanks! I think I know what is going on. From the logs, it seems that it is just the analog stick which is causing issues. Are you able to map the other buttons on the controller, apart from the analog stick?
> 
> Do not touch the analog stick before you attempt to map the other buttons.

Yeah! It looks like if I start mapping the other buttons first that works - everybody but the analog stick just like you said. Any suggestions as to what I can do here to get the analog stick working?

**Comment by shysaur** [comment] 2019-10-19 17:10
Your issue is caused by an unforeseen interaction between Catalina and the OpenEmu controller database, so there is nothing that you can try for yourself to fix it.

However, I am preparing a test build of OpenEmu with a fix for you to try, so stay tuned for just a little longer.

**Comment by joeauty** [comment] 2019-10-19 17:12
> Your issue is caused by an unforeseen interaction between Catalina and the OpenEmu controller database, so there is nothing that you can try for yourself to fix it.
> 
> However, I am preparing a test build of OpenEmu with a fix for you to try, so stay tuned for just a little longer.

Thank you!

I hope working through this issue will be useful for others too, whether it is a conditional for Catalina + Adaptoid, or something broader in scope. More than happy to stay tuned and help in any way I can.

**Comment by shysaur** [comment] 2019-10-19 17:23
Here's the link to the test build:
https://transfer.sh/BNYRO/OpenEmu-74236953-issue3994-1.app.zip

(The link will expire in 2 weeks)

**Comment by joeauty** [comment] 2019-10-19 18:04
So far the build works great! I'll play some more and let you know if I come across any problems...

**Comment by joeauty** [comment] 2019-10-19 20:22
Yup, all cool...

**Comment by shysaur** [comment] 2019-10-19 20:28
Great! Thanks again for the help.

The fix for this issue will be included in the next release.

**Closed by shysaur** 2019-10-19 20:28 UTC
