### ISSUE TITLE
Analog sticks don't work properly for Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by TheBestCheese17** [OpenEmu/OpenEmu#3574] opened 2018-03-26 23:07 UTC
For some reason my analog sticks for Nintendo 64 games don't work as intended. When I play Super Mario 64, Mario can move, but he doesn't move at full speed and going left makes him move even slower. My version of OpenEmu is the latest and my Mac is version 10.13.2. Also my version of Mac is a Mac Air. Please let me know, thanks.

**Comment by clobber** [comment] 2018-03-26 23:15
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3102

**Closed by clobber** 2018-03-26 23:15 UTC
