### ISSUE TITLE
jerky scrolling / judder

### ISSUE THREAD

**Issue by strikerdark** [OpenEmu/OpenEmu#1867] opened 2015-03-18 15:48 UTC
I've been having this problem for months in Openemu.  A lot of the times when the screen scrolls in a super nintendo game (mario all stars for example) it looks juddery/jerky. I only use openemu for snes games and this happens on both of the snes cores. To put this in context, I was having exactly the same issue on Windows emulators like Higan and Snes9x. However I was able to fix the issues over there by enabling vsync on both emulators

Now I've read about openemu, and apparently vsync is enabled by default. But is it really? I can tell you that the judder and jerkiness definetely looks like too many frames are being rendered. Maybe there is a bug thats disabling vsync?

This is my system

IMac (27inch, late 2012)
Version 10.10.2
Processor: 3.4 GHz intel core i7
Memory: 32 GB 1600 MHz DDR3
Graphics: Nvidia Geforce GTX 680MX 2048 MB

**Comment by clobber** [comment] 2015-03-18 19:52
Vsync is always enabled, but the issue you are seeing is brought on by something else.

While you're having the issue, run "sudo spindump" in Terminal and then link the file it generates back here via gist.github.com, dropbox or transfer.sh

**Comment by strikerdark** [comment] 2015-03-18 20:20
Ok i did the command. Here is the file it generated https://www.dropbox.com/s/k0e19bahdcrsq40/spindump.txt?dl=0

**Comment by clobber** [comment] 2015-03-18 23:57
Mednafen is using most of the CPU time. Which version of the Mednafen core port are you using and did you compile it yourself?

**Comment by clobber** [comment] 2015-03-19 00:11
Edit: Sorry, posted in the wrong ticket.

**Comment by mrvacbob** [comment] 2015-03-19 06:01
When you Vsync a Windows emulator, I think it might lock the emulated framerate to 60fps. We draw at 59fps, which is accurate to the SNES but unfortunately is not how often the display draws, so it won't scroll perfectly smoothly. The fix would be to add a mode which plays the game about 1% slower.

It doesn't seem like there is any particular CPU usage/GPU frame dropping issue here, though I see you're using one of the Cg shaders. If you try Nearest Neighbor does it look any better in motion? There could be a shader bug.

**Comment by strikerdark** [comment] 2015-03-19 06:07
yeah im pretty sure higan uses 60 fps, but i could be wrong. (at least it says 60 fps on the higan fps counter).    I tried Nearest Neighbor and the issue still happens

**Comment by clobber** [comment] 2015-03-20 23:06
@strikerdark I don't expect this build to change anything at all since the issue is related to syncing, but I'm curious if anything changes for you so give this one a try.

https://transfer.sh/pVz8d/openemu-1.0.4-no-clientstorage.zip

**Comment by strikerdark** [comment] 2015-03-20 23:38
@clobber As you expected it did not change anything, the issue still happens

**Comment by clobber** [comment] 2015-03-21 06:13
Okay, thanks for testing. We're aware of the general issue and we'll have to add some syncing to video refresh rate as mrvacbob mentions -- it kinda ties into other optimizations we need to make that we're tracking in another ticket.

When the emulator core's rate differs from your display's rate you'll get frame dropping or doubling, depending on the difference in rates. Some applications might block while waiting for vsync in the render loop, which could explain what you experienced in the Windows ports, but I'm not sure that's the best way to do it.

To test another method, I set the frameInterval for SNES9x to my display's rate returned by `CVDisplayLinkGetActualOutputVideoRefreshPeriod` which turned out to be 1 / 0.016605 = 60.223053. Once SNES9x was running at the same rate as my display it was scrolling pretty smooth. I used this test ROM that displays a checkerboard pattern scrolling one pixel up and left every frame: http://snesemu.black-ship.net/misc/roms/bsnesdemo.sfc

Display refresh rates can diverge quite a bit per-device as I've seen at least as low as 59.709659 on one machine. So to fix we'd need to adjust rates for NTSC games (on systems running between ~59-61 fps) so we're running them at the refresh rate of the display but will probably also have to adjust the audio sample rate as well.

Just curious, could you run this small app so I can get the refresh rate of your display? Maybe we can do a test build of SNES9x and see how it runs on your machine with a matching rate. Just unzip and then right click and select open to run http://cl.ly/3M3L1F1D0y41

**Comment by strikerdark** [comment] 2015-03-21 06:26
59.940061 on my TV  and i got 59.950550  on my imac display.  i usuallly use my tv to play games, but ive been testing on both just to be sure.

**Comment by clobber** [comment] 2015-03-21 06:42
Alright that explains the stuttering then. 59.940061 or 59.950550 vs SNES9x running at 60.098.

Here's a build of SNES9x set to 59.950550 that you can test on your iMac. It should be improved. Maybe also run it in that other test build of OpenEmu and use Nearest Neighbor for the filter. Download and unzip, then place in the folder `~/Library/Application Support/OpenEmu/Cores` (~ meaning your Home folder where ~ is your username. Guide here if you don't already know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)

SNES9x build for iMac at 59.950550 fps: https://transfer.sh/ZvLBD/snes9x-test.zip

**Comment by clobber** [comment] 2015-03-21 06:44
Oh, and be sure to have your games running with SNES9x. Launch a game and from the HUD bar select the cog wheel icon, "Select Core" and tick SNES9x.

**Comment by strikerdark** [comment] 2015-03-21 07:38
@clobber i got some interesting results:  if i use the updated core with the regular Openemu i get some weird stuttering thats different of how it was before. However, if i use it with the other version of Openemu you gave me the scrolling is close to perfect.  I say close cause there is still a very small judder in the background images but maybe thats  a different issue or something thats completely normal and supposed to happen. 
Also, sound is weird/off sounding on either version of OpenEmu using the updated core. (which i think you hinted at that it would happen)

**Comment by clobber** [comment] 2015-03-21 08:30
Huh interesting. Thanks a lot for testing!

Alright so GL client storage was definitely an issue on your GPU too, which i disabled in that other version of OpenEmu. Seems we'll just remove that completely then otherwise we're playing whack-a-mole with the various GPU's. Hopefully we can get direct to IOSurface rendering.

Not sure about that small judder in the background images, but good to hear its scrolling close to perfect with the timing change. And yeah, for the sound we'd also have to adjust that too if we do use this method to sync video.

So for now, use that 'other' version of OpenEmu since that fixes at least one problem with video related to GL client storage. Next version of OpenEmu will have client storage use removed completely, so best to use that other build. I don't know if we'll get video syncing fixed in time though and there are definitely some other optimizations we need to do as well. You may want to switch back to the other SNES9x version (you could delete the one in the folder and re-download from Core Preferences in the app) or Higan so sound will be okay and just deal with the slight jerky frames for a while.

I'll close this ticket and reference it with an earlier one (#967) with the same problem (you can still post in this thread), but technically the problem isn't 'fixed' yet. We'll add it to the list of optimizations to do and keep an eye on it. Thanks again for all the testing.

**Closed by clobber** 2015-03-21 08:30 UTC

**Comment by Truesyndo** [comment] 2015-12-21 04:52
can you reupload the clientstorage file please id like to enjoy the openemu program

**Comment by Samberto** [comment] 2018-01-14 05:58
Having this very issue with 2.0.6.1. Am I missing something, or is the fix still in the works?
Thanks. 
Late 2012 iMac running 10.13.2. Refresh rate of 59.950550
