### ISSUE TITLE
Feature Request - Library view Controller Menu Support

### ISSUE THREAD

**Issue by bomer** [OpenEmu/OpenEmu#1955] opened 2015-06-24 12:35 UTC
Be great to be able to swap roms using the PS4 controller! The cover flow UI is ok but it'd be lovely to see a version of the Library I could navigate and launch games with just the controller. Amazing Dualshock 4 support though as far as games go!

**Comment by cyco** [comment] 2015-06-24 16:29
Yep, that would be awesome. We'd need some awesome designers with plenty of time to waste to make it happen. If you know any send them over to #OpenEmu on freenode ;)

Duplicate of #401 btw.

**Closed by cyco** 2015-06-24 16:29 UTC

**Comment by edwonia** [comment] 2015-06-27 13:09
I might be able to do a few concepts for this, I'm a designer. You can see my work here: www.edwon.tv

**Comment by Yahkob** [comment] 2021-08-02 20:41
Honestly I think anything is better than nothing here 😢 

I don't need anything fancy just the existing UI with gamepad support and I'd be happy
