### ISSUE TITLE
Pokemon Black Emulator suddenly stopped working

### ISSUE THREAD

**Issue by Tfp007** [OpenEmu/OpenEmu#3617] opened 2018-05-02 13:54 UTC
So I left my computer for a bit to run some errands and it was only left with my charger. When I came back all of a sudden, the keys stopped working. I tried restarting my computer and quitting all the other softwares, but it didn't work. Can someone please help me I love the game so much and I can't risk of having it not work thank you!

My software is a macOS high sierra version 10.13.3.

**Comment by clobber** [comment] 2018-05-02 14:01
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 
* "Please search before opening a new issue."
* "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."

Duplicate of #3536

**Closed by clobber** 2018-05-02 14:01 UTC
