### ISSUE TITLE
Window fills red on 2017 iMac with Mojave

### ISSUE THREAD

**Issue by hansomdevil** [OpenEmu/OpenEmu#3822] opened 2018-12-17 19:46 UTC
Summary of issue

Anytime I start up OpenEmu, some portion of or all of the library window is filled with red.

<img width="1508" alt="screen shot 2018-12-17 at 1 33 58 pm" src="https://user-images.githubusercontent.com/20796275/50110892-f67aa880-0200-11e9-966f-8fdeb78cf61b.png">
Moving the games library pane clears things back to normal.
I think this started after I switched to Mojave.

# Steps to reproduce

Start the program in Mojave

# Expected Behavior

The games list to appear as normal.

# Observed Behavior

Games list displays a varying amount of empty red fill.

# Debugging Information

- OpenEmu Version: 2.08. Also happened in 2.07
- macOS Version: 10.14.2

**Comment by robotoad** [comment] 2018-12-17 21:17
This should have been fixed for Mojave, and this is the first report I've heard of it still occurring despite our grid view hack. Unfortunately, I'm not able to reproduce it on my machine. Is there anything unique about your hardware and software configuration?

**Comment by hansomdevil** [comment] 2018-12-17 21:40
I got the machine in early November, so I haven't really changed things around that much. It has the 580 radeon upgrade. I keep screen sharing on (turning it off doesn't change the bug), I have a few brew packages installed, Crossover, and VmWare Fusion.

**Comment by hansomdevil** [comment] 2018-12-17 22:13
I should say that the library and openemu was imported from an older computer. Not sure if that is helpful.

**Comment by robotoad** [comment] 2018-12-18 00:44
Do you mind downloading and running this test build to see if it resolves the issue?
https://transfer.sh/u7rh8/OpenEmuGridViewTest.app.zip

**Comment by hansomdevil** [comment] 2018-12-18 01:05
That fixed it. No more red.

**Comment by robotoad** [comment] 2018-12-18 01:10
Fixed in 046c627.

**Closed by robotoad** 2018-12-18 01:10 UTC

**Comment by robotoad** [comment] 2018-12-18 17:37
I'm testing a more elegant fix for the grid view, and I was wondering if you wouldn't mind running this to verify that your issue is still resolved. I'd appreciate it! 

https://transfer.sh/3oKb7/OpenEmuGridViewFix.app.zip

**Comment by jonathanhirz** [comment] 2019-01-04 17:44
I know this is closed, but I see a similar issue on my computer (mac mini, macOS 10.14.2), except the fill isn't red, it's just the background color of the games view (so it looks like there are no games). Scrolling fixes this. Also, if I click in the games view, the highlighted item on the sidebar (whichever console I have selected) becomes blank.

**Comment by robotoad** [comment] 2019-01-04 17:49
The issue is better addressed by 9f476506efd57d67e8e8a19a51560ec4d25dde5f, which uses a different solution than before.
