### ISSUE TITLE
Built-in Keyboard not working!

### ISSUE THREAD

**Issue by ChiDeath** [OpenEmu/OpenEmu#2333] opened 2016-01-08 05:17 UTC
I compiled OpenEmu to be safe and up to the latest version, but when I start the game, the keyboard does not work. I also can not configure the controls, because it will not respond either. I have looked everywhere for a fix, but no luck. Can anyone please help me find a way to fix this? or does anyone have any information on when it will be fixed?? 

Thanks so much in advanced!!

**Comment by clobber** [comment] 2016-01-09 20:20
This has come up several times in the past, usually related to some other open application causing interference so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2016-01-09 20:20 UTC
