### ISSUE TITLE
GBA sound does not play in Ver. 2.4 to 2.4.1 /MacOS 12.7.3

### ISSUE THREAD

**Issue by NBEGnHsx** [OpenEmu/OpenEmu#4972] opened 2024-01-26 15:48 UTC
# Steps to reproduce
1. Start OpenEmu.
2. Open the Gameboy Adbance list.
3. Launch Gabeboy Adbance game from the list.

# Expected Behavior
I would expect sound to play in GBA games.

# Observed Behavior
Sounds from GBA games either do not play at all or play only for a few seconds at startup.

# Debugging Information
- OpenEmu Version: 2.4 - 2.4.1
- macOS Version: 12.7.3

**Comment by clobber** [comment] 2024-01-28 01:56
Duplicate of #4955

**Closed by clobber** 2024-01-28 01:56 UTC
Labels: duplicate
