### ISSUE TITLE
Keyboard not working in open emu expirmental even with chrome closed

### ISSUE THREAD

**Issue by jt19731** [OpenEmu/OpenEmu#2181] opened 2015-12-02 11:09 UTC
Hi, 

Problem as above, running Yosemite 10.10.5 (14F27)

Many thanks, 

John

**Comment by clobber** [comment] 2015-12-02 20:18
This has come up several times in the past, usually related to some other open application causing interference so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Closed by clobber** 2015-12-02 20:18 UTC
