### ISSUE TITLE
Mouse input won't work on supported systems with DualShock 4 connected

### ISSUE THREAD

**Issue by 3ntrax** [OpenEmu/OpenEmu#2636] opened 2016-07-13 15:40 UTC
When using OpenEmu 2.0.2 to play Nintendo DS games i won't register mouse inputs. 
When asked to press here or there it doesn't work.

Installed OpenEmu 2.0.1 no problem at all, it work's perfect. 
Any thoughts about to get it working in 2.0.2 or is it a bug?

**Comment by clobber** [comment] 2016-07-13 17:34
Please provide an example NDS game where mouse input works on 2.0.1 but not on 2.0.2.

**Comment by 3ntrax** [comment] 2016-07-13 17:54
those are the games that i tested and didn't work on 2.0.2

Ace Attorney Investigations : Miles Edgeworth
Apollo Justice : Ace Attorney
Blue Dragon Plus
Cooking Mama
Cooking Mama 2 : Dinner With Friends
Cooking Mama 3 : Shop & Chop
Trauma Center : Under The Knife
Trauma Center 2 : Under The Knife 2

**Comment by clobber** [comment] 2016-07-13 19:24
I tested the US releases of all 8 of these games - mouse input, both trackpad and wireless, works in OpenEmu 2.0.2 with the Desmume 0.9.11 core plugin.

Only game I know of that has a legitimate problem, regardless of OpenEmu version, is WarioWario: Touched due to bugs with the Dynamic Recompiler which is enabled by default in our core plugin. Note: Desmume standalone does not have the Dynamic Recompiler enabled by default.

**Comment by 3ntrax** [comment] 2016-07-14 06:59
It seems i'm not the only one with this problem , saw reports from other users with the same issue mouse input not working in DS games in version 2.0.2 , in fact there isn't any game that works where you need to use input with mouse.

**Comment by clobber** [comment] 2016-07-14 20:27
@3ntrax Are you using a DualShock 4 gamepad by chance?

**Comment by 3ntrax** [comment] 2016-07-15 02:04
Yes indeed i'm using a DualShock 4 gamepad connected with USB

**Comment by clobber** [comment] 2016-07-15 02:32
Thanks for confirming. I was able to replicate mouse input not working when a DualShock 4 is connected (paired or via usb).

It broke in this commit: https://github.com/OpenEmu/OpenEmu/commit/cbe4e85694ffecc9740c862eb0d04be5b9af5995

**Comment by clobber** [comment] 2016-07-15 05:38
Update: So this is weird. After testing several builds and reverting various commits, I can no longer replicate the problem on a completely unchanged build of OpenEmu 2.0.2 with the DualShock 4 paired - it all works fine now as if nothing was wrong, even the other N64 issue. Starting to think there is an OS X bug with this device.

**Comment by 3ntrax** [comment] 2016-07-15 13:30
In fact i'm using the latest OSX El Capitan 10.11.5, i didn't install anything fancy, clean El capitan install , and installed OpenEmu that's it. I tried several times installing 2.0.2, removing 2.0.1 first with no positive result. I've updated within openemu with no positive result. I tried using another mouse same result. I tried another brand mouse same result.

**Comment by clobber** [comment] 2016-07-15 19:55
I've found that when I can replicate the crash, sometimes if I disconnect the device (Bluetooth -> Device -> Disconnect), I get the following crash: https://gist.github.com/anonymous/647e5ef9841b3affa71bfa9f3553194b

**Comment by clobber** [comment] 2016-07-16 02:59
@3ntrax, @demraldes:

Okay, so I started noticing a strange pattern:

With my web browser open (Firefox) and my DualShock 4 paired, mouse input would register very intermittently, barely enough so that it would appear non functional. You can click repeatedly and eventually get it to register a click.

I restarted my machine and didn't open anything besides OpenEmu. With my DualShock 4 paired, mouse input would register okay but slightly delayed, or not for every frame, as compared to when I had the DualShock 4 disconnected.

I then opened Firefox and suddenly mouse input would stop registering, or very intermittently again. This is a very strange problem - maybe somewhat related to Firefox's HTML5 Gamepad API?

As for testing the mouse input and overall responsiveness, please use this NDS test ROM and see if you can replicate the same results as me. Click and move your cursor in a "figure 8" motion to compare drag smoothness when only OpenEmu is running with the DualShock 4 connected and then again when disconnected.

NDS test rom: https://transfer.sh/wkaCv/touch-test.nds (link valid for 14 days).

**Comment by 3ntrax** [comment] 2016-07-16 13:01
Ok so for the testing

I tried with OpenEmu 2.0.1
DS4 connected --> OK
DS4 disconnected --> OK

I tried with OpenEmu 2.0.2
DS4 connected --> NOK (not working)
DS4 disconnected --> OK (so it's for sure related to DS)

**Comment by demraldes** [comment] 2016-07-16 14:42
I had the same results.  Didn't try it on 2.0.1, but as far as 2.0.2 goes the DS4 controller is definitely the problem.  Opened the rom with DS4 connected, no mouse response; unplugged the DS4 with the rom still running, mouse started to work immediately.

**Comment by clobber** [comment] 2016-07-16 14:50
Um, guys...I didn't say to test on 2.0.1...we already know this is an issue exclusive to 2.0.2.

Re-read my post above where I said I restarted my machine and ran OpenEmu with all other apps closed. Those are the test cases I want you to try and replicate.

**Comment by 3ntrax** [comment] 2016-07-16 15:51
Sorry my bad.

Here are the test results. After i restart mac and use OpenEmu 2.0.2

DS4 unpaired with bluetooth --> mouse works perfect with testrom.
DS4 paired with bluetooth --> mouse works but not as smooth as above. slight delay in movement.

But

DS4 connected with USB cable --> mouse won't work with testrom no movement at all.
DS4 disconnected from USB cable --> mouse works perfect with testrom.

**Comment by demraldes** [comment] 2016-07-16 23:30
Right, so I tried bluetooth vs USB with the DS4.  When pairing the controller via bluetooth the mouse seems to work just as well as when the controller is disconnected, but when the DS4 is connected via USB I completely lose mouse response on the touchscreen.

**Comment by clobber** [comment] 2016-07-16 23:40
@demraldes What about after restarting your machine and with nothing else running besides OpenEmu? That was the main thing I wanted everyone to replicate, although the bluetooth vs usb is interesting - I've had different results.

**Comment by spacecowgoesmoo** [comment] 2016-08-01 05:16
JFYI, I have a Wii U Pro controller and am having the same bug. I replicated it with no other apps open, and after a clean restart. 

There are no mouse inputs registered while my controller is active but if I open up System Preferences > Bluetooth and manually disconnect the controller, the stylus instantly works again. I downgraded to 2.0.1 for now and the problem is gone.

**Comment by clobber** [comment] 2016-08-02 06:24
Fixed in https://github.com/OpenEmu/OpenEmu/commit/3032021828c473dbfdd444f04eb72da2bb6d5433 for next release.

**Closed by clobber** 2016-08-02 06:24 UTC
