### ISSUE TITLE
keyboard not working

### ISSUE THREAD

**Issue by iandonegan8** [OpenEmu/OpenEmu#2652] opened 2016-07-19 01:11 UTC
Hi my keyboard for mac OS X El Capitan 10.11.5 which is used for openemu 
 is not working. I got the new update just don't now what to do. Please help me and I would appreciate if someone could reply soon. Thx

**Comment by joshvickerson** [comment] 2016-07-19 14:05
I believe I experienced this last night as well, though I'm running the macOS beta. I was playing a game and after a little while my keyboard simply stopped working, not just in OpenEMU but across the whole system.

Restarting my Mac fixed it, thankfully. I know this report isn't particularly helpful to determining what happened, but should it happen again, what can I do to investigate a possible cause?

**Comment by clobber** [comment] 2016-07-19 17:57
@iandonegan8 Need to use the search.

This has come up several times in the past, usually related to some other open application causing interference (Chrome or 3rd party terminal apps being common culprits) so you will need to close everything until you find what it is. If you search the issues you should be able to find related issues and possibly a solution. Closing because we don't need another duplicate of these open.

**Comment by clobber** [comment] 2016-07-19 17:58
@joshvickerson 

>not just in OpenEMU but across the whole system.

That isn't an OpenEmu problem.

**Closed by clobber** 2016-07-19 17:57 UTC

**Comment by Botanner007** [comment] 2016-07-22 04:47
Still isn't working for me... no programs running in the background

**Comment by iandonegan8** [comment] 2016-07-24 22:09
i fixed it thx i think it was what you said sorry for the late reply
