### ISSUE TITLE
OpenEMU 2.0.6+ deletes save states

### ISSUE THREAD

**Issue by cobrapg** [OpenEmu/OpenEmu#3585] opened 2018-04-03 20:00 UTC
Launching any game on version 2.0.6 and and 2.0.6.1 results on its associated save states getting deleted. This happens at launch. 

Verified this by opening the folder directly on the Mac and watching as OpenEMU is launched. Any save states and quick saves are preserved while playing the game and when closing the program. Once launched the files are removed. 

Version 2.0.5 doesn't exhibit this behavior.

**Comment by clobber** [comment] 2018-04-03 20:06
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md)
- "Please search before opening a new issue."

Duplicate of #3436

**Closed by clobber** 2018-04-03 20:06 UTC
Labels: duplicate
