### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by JuanluR8** [OpenEmu/OpenEmu#3396] opened 2017-11-13 12:32 UTC
I´m on High Sierra update and openemu crashes while i'm playing.. the screen freezes and i cant do anything except a force output...

**Comment by clobber** [comment] 2017-11-13 17:18
This isn't enough information to troubleshoot. Please provide a crash log and exact details to replicate the crash/freeze. Also provide details about your Mac (system specs, GPU, model) and versions of OpenEmu and High Sierra you are using.

**Comment by JuanluR8** [comment] 2017-11-13 20:23
My Mac is a Macbook pro Mid 2014, 2,6 Ghz Intel i5, 8Gb RAM 1600 MHz DDR3 using macOS 10.13.1 and Openemu v 2.0.5.

It's just I play and it suddenly freezes.

I got this error:

Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery

**Comment by clobber** [comment] 2017-11-13 20:35
Still not providing enough details... What is your GPU? Does this **always** happen? Is it with a certain system/game? Where did you get that error message? In Console?

**Comment by clobber** [comment] 2017-11-13 20:37
Also, screenshot the error message where you see it.

**Comment by JuanluR8** [comment] 2017-11-13 22:33
My GPU is Intel Iris 1536 Mb.
The freeze is always while i'm playing, doesnt matter what game, sometimes after 5 min, other around 15-20, but always gets freeze.

Y got that message in Console, this is the screen after crashing (while i was playing Final Fantasy tactics advance):

<img width="1280" alt="captura de pantalla 2017-11-13 a las 23 27 56" src="https://user-images.githubusercontent.com/17733364/32752747-a173ec72-c8ca-11e7-84f8-24ccc64db0ed.png">

PS: I used to play on Openemu last summer and it didnt happen, but i dont remember what version I got installed or what games i played

**Comment by clobber** [comment] 2017-11-13 23:21
The message you are seeing isn't coming from OpenEmu, but the freeze you are experiencing is a duplicate of issue #3365.

Please download this test build and tell me if the crash/freeze is fixed: https://transfer.sh/rMM2n/OpenEmu_highsierra_hangfix_test.zip

**Comment by JuanluR8** [comment] 2017-11-14 02:48
I've been playing for 2 hours without crash or freeze. Everything ok for the moment!

**Comment by clobber** [comment] 2017-11-14 16:55
Great - thanks for testing! This fix will be out with our next release.

**Closed by clobber** 2017-11-14 16:55 UTC

**Comment by PlutoX86** [comment] 2017-11-19 12:15
Regarding the "High Sierra Hangfix Test" version,.. I'm not sure if it's relevant for the OE dev team, but i'd like to know if anyone else can't start Nintendo DS games and/or have no sound in mame/arcade games with it?

(I recently compiled the latest build of OE.. and NDS games are def. starting again, but there's still no sound in mame/arcade games)
