### ISSUE TITLE
N64 Audio Problem (constant tone glitch/or silence)

### ISSUE THREAD

**Issue by arianoel** [OpenEmu/OpenEmu#4647] opened 2022-01-02 03:34 UTC
Summary of issue:

Every time I load a N64 rom, the audio will begin to glitch shortly after gameplay. It freezes on a constant tone. The game is still playable, however the audio only fixes after closing the game and reopening, only to happen again and again. Sometimes instead it goes silent

First, I will open a game for N64 (other consoles seem fine). Then as I am playing normally, within a couple minutes of gameplay the audio just freezes on whatever sound is currently running. I think it's looping the audio tick or something, but it creates a single tone of the culmination of sounds happening at the point that it glitches. The gameplay resumes as normal, but the audio is horrible and cannot be stopped. I can turn the sound down and up as normal, but if I want it to stop I have to completely exit the game. Upon reopening I can resume as normal very briefly before it begins happening all over again. It makes gameplay borderline impossible. The only option is to turn the sound all the way down and play while it's glitching or to play with a horrendous buzzing sound. Either this will happen or the game will go silent with no resolve

# Expected Behavior

The game audio to function normally

# Observed Behavior

The game audio cuts out indefinitely or turns into a constant buzzing

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: Monterey 12.1

**Comment by clobber** [comment] 2022-01-02 03:38
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4631

**Closed by clobber** 2022-01-02 03:38 UTC
Labels: duplicate
