### ISSUE TITLE
Feature request - User able to specify MAME core version 

### ISSUE THREAD

**Issue by nickd3000** [OpenEmu/OpenEmu#4582] opened 2021-08-18 13:00 UTC
AT the moment I can download an older MAME Core version, add it to the core folder and lock the files within it to prevent OpenEmu from auto updating over the older core.  Would it be possible to add some UI to specify the MAME Core version instead?

best regards
Nick

**Comment by clobber** [comment] 2021-08-18 22:58
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4423

**Closed** 2021-08-18 22:58 UTC
Labels: question, duplicate
