### ISSUE TITLE
"mGBA core has quit unexpectedly after loading a save state" error on v2.3 using MacBook 10.14.6

### ISSUE THREAD

**Issue by emieliason** [OpenEmu/OpenEmu#4393] opened 2020-12-29 18:50 UTC
"The mGBA core has quit unexpectedly after loading a save state" error occurs whenever I try to open any GBA ROM. Clicking "reopen without loading state" gets me to "The mGBA core has quit unexpectedly" [please submit feedback] error. Couldn't find answers anywhere else. Using mGBA core 8.4... it was working fine until the 2.3 update, I think.

**Comment by clobber** [comment] 2020-12-29 18:56
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4352

**Closed by clobber** 2020-12-29 18:56 UTC
Labels: duplicate
