### ISSUE TITLE
N64 Rewind feature does not work

### ISSUE THREAD

**Issue by Carl-wheezer** [OpenEmu/OpenEmu#3832] opened 2019-01-04 11:45 UTC
The Mupen Core does not rewind at all. I press my rewind button (The C button on my Wiichuck) and it doesn't rewind at all. I tried with both experimental and ful releases.
Please note I am horrible with Mac (I'm using my friend's mac for this, don't own one 🙁) so be gentle (or don't because that's fine too lol)

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Go to any N64 game
2. Press whatever is your rewind button

# Expected Behavior

Should rewind just fine 

# Observed Behavior

Does not rewind. Causes a small glitch where the game freezes for ~13 frames (yes i counted it) and then fast forwardses (is that a word?) to catch up.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.2

**Comment by Carl-wheezer** [comment] 2019-01-04 12:17
OKAY, i just found out that others have this issue! But, the weird bug i mentioned hasnt happened for qnyone else....

**Comment by clobber** [comment] 2019-01-04 15:55
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #3658

**Closed by clobber** 2019-01-04 15:55 UTC
Labels: duplicate
