### ISSUE TITLE
Can't Map Gamecube Controllers

### ISSUE THREAD

**Issue by Surlevif** [OpenEmu/OpenEmu#1773] opened 2015-01-07 01:13 UTC
Hello,

I just got two gamecube controllers and this adapter : http://www.amazon.com/gp/product/B0089NVTDM/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

The controllers show up as USB Gamepad but only the triggers are recognized.  I then installed USB Overdrive to test the controllers and all the keys are recognized and working fine.

Is it a know issue ? Did anybody else managed to get gamecube controllers to work with OpenEmu ?

**Comment by cockpilot** [comment] 2015-02-08 07:59
I have this same problem. I have a Mayflash, openemu and a macbook. Only the Right bumper registers, but it works perfectly fine when I'm playing on Dolphin

**Comment by csgregorian** [comment] 2015-02-27 02:17
Same for me but with the PC/WiiU 4-controller adapter.  Definitely not a localized issue.

**Comment by frankymacster** [comment] 2015-03-10 02:05
Same problem with the Mayflash GC adapter... Have you tried https://github.com/OpenEmu/OpenEmu/pull/1607 ? Only the triggers work...

**Comment by ngude** [comment] 2015-05-09 17:38
same problem here. multiple controllers hooked up to this adapter work fine in mame as well FYI,

**Comment by nicoNaN** [comment] 2015-09-07 01:35
Same issue here on 10.11

**Comment by cpacejo** [comment] 2015-12-06 02:51
I've hit this too.  Basically, configuration works until I accidentally hit one of the shoulder buttons.  Then I can't assign anything *except* the shoulder buttons.  Even assigning buttons for non-GC controllers stops working!

**Comment by cpacejo** [comment] 2015-12-27 19:54
Does the reworked input system in 2.0.1 fix this?  OpenEmu is basically unusable for me with this issue.

**Comment by wbobeirne** [comment] 2016-02-08 06:33
Can confirm that this problem still exists. Dolphin reads all inputs fine, but OpenEmu gets locked to triggers-only after using them once while configuring controller.

**Comment by SoaringHawk820** [comment] 2016-02-19 03:44
Will we ever see support for the first party Wii U GameCube adapter?

**Comment by SoloKeita** [comment] 2016-04-26 06:37
I have made a temporary (I hope it's temporary) workaround.  I experienced this bug and knew right away it was a software bug and knew it was a problem with the front-end user interface.  Here's what to do;

1.  Quiet OpenEmu and make your way to:
/Volumes/Macintosh\ HD/Users/(username)/Library/Application\ Support/OpenEmu/Bindings 

2. In the "Bindings" folder you will find a file titled "Default.oebindings".  Go ahead and change the name of that file to "Default.oebindings.originalbackup" 

3. Then, unzip the file I have attached to this post titled "Default.oebindings.zip" and put the file "Default.oebindings" into the "Bindings" folder.

4. Keep that .zip I just gave you and put it somewhere else for safe keeping.  Don't ever go to change the controls in OpenEmu or you will have to delete the Default.oebindings file from the "Bindings" folder and re-enter the one I just gave you.

I just made this workaround last night and when I tested it it seemed to work great.  Let me know if you guys have any troubles.  And I really hope this bug is fixed soon because it does suck.  OpenEmu is an awesome and beautiful emulator but it is so buggy and unreliable.

[Default.oebindings.zip](https://github.com/OpenEmu/OpenEmu/files/236020/Default.oebindings.zip)

**Comment by braco** [comment] 2016-06-09 14:44
Same issue? #1607

**Comment by sethten** [comment] 2016-08-14 16:07
Same setup, same problem. August 2016. Mayflash GC controller adapter for USB.

**Comment by Kabaaz** [comment] 2016-08-16 09:10
Same issue with the official Wii U GameCube Adapter... It's not recognized when plugged in. Everything's fine with Dolphin 5.0, all buttons and even rumble feature are responsive! I've just installed the driver on this page : https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin. Hope it'll be included in a future release... Love the GameCube pad ;-)!!!

OpenEmu v2.0.3
Mac OS X 10.11.6

**Comment by sethten** [comment] 2016-08-17 12:36
@Kabaaz Thanks for the help. I have both the blue two-port adapter and 4-port wii u/pc adapter. I also tried the second, both usb ports, switch in both positions, all four ports in each situation. I did manage to find one combination that worked in Dolphin. Well, it worked on the controller setup, the buttons had no effect once the emulation began. Leaving everything the same, there was still no response in OpenEmu besides the right analog trigger. I added that kext and upgraded to Dolphin 5.0 to test.

**Comment by clobber** [comment] 2016-08-17 17:54
Hello everyone with this issue, please post a link to your exact adapter that can be purchased. We cannot diagnose the problem if we don't have the adapter or even know which one.

Now for the **Official GameCube Controller Adapter for Wii U**, that will likely remain unsupported as it is not an actual HID device and would need a driver built into the app.

**Comment by Kabaaz** [comment] 2016-08-17 18:45
Hi clobber,

Thanks to you and your OpenEmu team for this great work... Keep up! And so no support for the Official GameCube Controller Adapter for Wii U... I understand though, I'll try with one of these Mayflash adapters and will come back here from time to time to post and see how it's going! According to previous posters, one (or both) of the triggers is responsive with Mayflash... That's a start ;-)!

**Comment by sethten** [comment] 2016-08-17 22:22
http://www.mayflash.com/Products/PCUSB/PC051.html (_not_ the [new one](http://www.mayflash.com/Products/NINTENDOWiiU/W013.html) with a switch)
http://www.mayflash.com/Products/NINTENDOWiiU/W012.html
https://www.nintendo.com/consumer/downloads/wave_english.pdf (yes I checked, rechecked, and checked again that they were on the same channel and I didn't inadvertently move the dial)
I found the same behavior of only the right analog trigger registering.

**Comment by SoloKeita** [comment] 2016-08-18 07:27
If you read my previous comment you will see that the adapters actually work fine and you can use them with SixtyForce without any problems.  It's actually the front end of OpenEmu that is having the problems.  I am able to use OpenEmu with the GameCube controller triggers by going into the backend and editing the Default.oebindings file manually. Download the file I uploaded and give it try (I only set it up to work for the N64 games).  OpenEmu has problems when you try and set up the GameCube controller in the app's preferences and it only messes up when you press or bump the L or R triggers during set up.

And Clobber, you should be able to get the OEM Nintendo WiiU adapter to work as well because Dolphin was able to support it.  It would be nice to just put Dolphin in OpenEmu and kill two birds with one stone.  Then we could use the WiiU adapter and play GameCube / Wii games in OpenEmu.

**Comment by clobber** [comment] 2016-08-18 08:09
@SoloKeita You aren't adding anything to the discussion here. The workaround with the mappings is known, and the fact that the adapters work with other applications is irrelevant. Also, I don't care much for natively supporting the Official Wii U adapter (honestly, or GameCube controllers in general -- they are awful for retrogaming). I am simply asking for a list of devices that don't work and links to where they can be purchased, so that we might check them out eventually, to troubleshoot the problem. I also didn't care for your earlier comment where you made a brash generalization about the application being "so buggy and unreliable" due simply to your experience with an adapter. That certainly won't win you any favors.

**Comment by SoloKeita** [comment] 2016-08-18 08:49
@clobber Sorry for being a disturbance to your work then.  I'm just trying to do what I can to help.

This is the one I have.  I got it on eBay but those links expire so here it is on GearBest.  http://www.gearbest.com/video-game/pp_203817.html?currency=AUD&gclid=CjwKEAjwudW9BRDcrd30kovf8GkSJAB3hTxF6fUC4GzK6p8LKjWpDR6CZryRdUrlVk6V-0BGDLV8VhoCPcnw_wcB

**Comment by nicoNaN** [comment] 2016-08-19 04:24
GameCube controllers awful for retro gaming? What kind of sacrilege is this...? ;)

I have a Mayflash GameCube controller adapter purchased from Amazon: https://www.amazon.com/gp/aw/d/B00RSXRLUE/ref=pd_aw_sbs_147_3?ie=UTF8&psc=1&refRID=MMWMJCEN2KZE6TF32MGW

Neither the Wii U mode nor the "PC" mode work with OpenEmu - same trigger issues as described above. Both modes work in Dolphin.

@clobber Let me know if Amazon doesn't ship to wherever you are or you can't purchase this for some reason and I will personally send you one. I believe there are quite a number of people who want this feature - myself included! Willing to help however I can to make that dream a reality.

Cheers.

**Comment by seanskii** [comment] 2016-09-04 22:16
@SoloKeita I can't find the file to replace it. It's not showing up in OpenEmu at all. Any help?

**Comment by SoloKeita** [comment] 2016-09-07 06:09
@seanskii You can't find the file on your computer?

In **Finder**, press on "Go" in the menu bar, press & hold the "Option" key, then select "Library".  Then in that "Library" folder go to the "Application Support" folder.  In that folder is the "OpenEmu" folder and in there is the "Bindings" folder.

You may have to at least open OenEmu once for these files to appear.

**Comment by NorthWest1620** [comment] 2016-09-27 02:13
I've been wanting a fix for this for over a year. I'd like to play some old N64 games on this platform (4 player) and I already have the gamecube controllers.

I'm a developer and I'd happily contribute, but I don't know the first thing about emulator platforms, controller configuration, or whether the problem is with the software or the driver for the controllers themselves.

That said, I'd be willing to learn if anybody can point me in a starting direction. Between OpenEmu and Dolphin I can play pretty much every game I grew up with that is no longer convenient/possible to play on the original system. I'd rather use the $100 worth of controllers I already own. I can definitely see a gamecube controller being less than perfect for older systems, but it does really well for N64.

**Comment by pqhf5kd** [comment] 2016-10-07 14:14
@NorthWest1620 
The Official GameCube Controller Adapter for Wii U isn't a HID device so isn't compatible as a generic controller. 

By default macOS thinks it's a HID device, tries to read the commands, which obviously don't meet the standard, and fails.

Dolphin users use a Kext to stop macOS from believing it's a HID device:
https://forums.dolphin-emu.org/Thread-os-x-gcn-adapter-kext-testers-wanted

Then Dolphin has it's own driver from read the non-standand output:
https://github.com/dolphin-emu/dolphin/blob/ccfc0816974bde303ac62bfad019a41ff6fb13f0/Source/Core/InputCommon/GCAdapter.cpp

I'm not a developer and may have be wrong, in fact I'd say it more than likely I've used the wrong terminology, so please correct me if I'm wrong. But I'd love to use the the adapter with OpenEMU.

**Comment by DjDCH** [comment] 2016-12-23 17:53
I took a few hours to look into this issue, since I have the same problem. Here's my assessment of the situation.

* I have a MacBook running OSX 10.11.6
* I purchase the [Mayflash GameCube Controller Adapter 2 Ports on Amazon.ca](https://www.amazon.ca/gp/product/B00YH2TGYS/)
* I was able to make it work with Dolphin 5.0 in the WiiU mode using the special kext file
* I was able to make it work with ControllerMate 4.9.10 in the PC mode out-of-the-box
* I was only able to map the Right trigger (Ry+ and Ry-) in OpenEmu 2.0.4 (with the adapter in PC mode), nothing else

Many peoples and google searches pointed to PR #1607. I tried to make it work by reapplying the patch manually at the tip of the master branch, but I was not able to get a successful build (I was able to get one before I applied the patch). Also, to my understanding of the issue, this patch would not fix the issue, since it only add bindings to the controller database (which doesn't seems to be the right ones) and would not allow us to bind the controller manually.

Since my understanding and experience in Objective-C is pretty limited, I'm unable to dig into the code to find and fix the issue we're having.

But, as I saw in issues #792 and #2133, I should be able to provide more data that may help the resolution of the issue.

* Here's the [output](https://gist.githubusercontent.com/DjDCH/1f330ce25121c8a1d250f2a13da5496c/raw/system_profiler%2520SPUSBDataType) of the `system_profiler SPUSBDataType` command
* Here's the [device properties export](https://gist.githubusercontent.com/DjDCH/1f330ce25121c8a1d250f2a13da5496c/raw/MAYFLASH%2520GameCube%2520Controller%2520Adapter.plist) from HIDBrowser app
* Here's a [relevant extract](https://gist.githubusercontent.com/DjDCH/1f330ce25121c8a1d250f2a13da5496c/raw/Default.oebindings.diff) of the Default.oebindings file when the Right trigger (Ry+/Ry-) is binded
* All three files can be found in this [Gist](https://gist.github.com/DjDCH/1f330ce25121c8a1d250f2a13da5496c)

@clobber You might find useful the three files I linked above. Tell me if you need anything else.

**Comment by Fluxxed** [comment] 2017-02-04 16:55
@SoloKeita I tried what you did but it must have been patched because it didn't work. I have the same problem, here's my adapter: https://www.amazon.com/gp/product/B00RSXRLUE/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by MonsieurRomain** [comment] 2017-04-01 18:57
Same adapter https://www.amazon.com/gp/product/B00RSXRLUE/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1  same problem.

Note : This adapter as two mode (with switch interruptor) : WII U mode and PC mode.

**Comment by superresistant** [comment] 2017-04-17 10:33
Hello I found a fix that worked for me : 
 - Plug the first controller only on port 1 and check if it works.
 - Unplug it.
 - Plug the second controller on port 1 and check if it works.
 - Unplug and plug back the adapter with only the second controller on port 2.
The second controller should be working on port 2. Try again if it doesn't.
 - Plug both controllers and play.

**Comment by SoloKeita** [comment] 2017-07-07 19:24
@Fluxxed @seanskii   Sorry for the very long delay in replying.  I just went to use OpenEmu a couple weeks ago and it asked me to do the update so I did and the problem seems to be fixed for me.  Get the latest update and let me know if it works.  I think it still did weird things but I was able to remap my GameCube controller in OpenEmu.

**Comment by NorthWest1620** [comment] 2017-07-15 23:23
@SoloKeita I've never been able to get the controllers working using your fix, with any version of Open Emu.

**Comment by shax71** [comment] 2017-08-04 11:31
@SoloKeita the default.oebindings.zip fix above worked like a charm for me using a 3in1 MagicJoyBox. Much appreciated - thank you!

**Comment by SoloKeita** [comment] 2017-08-15 23:19
Hey @NorthWest1620 and @Fluxxed I think I know what your problem may be.  I think the file I made might not be working for you because your adapter has a different name than mine.  

Do this for me...
1. Open up your default.oebindings file with TextWrangler (App Store) (which apparently now is [BBEdit](https://www.barebones.com/products/textwrangler/download.html)).  
2. Look at the picture I've attached and notice how my adapter's name is "<key>OEGenericDeviceIdentifier_519691042816_26688926777345</key>"
3. Look at your default.oebindings file and tell me what your adapter's name is.

**Notice that my adapter actually has four names that are all one digit apart (45,46,47,48), these are for each individual port on my 4-port adapter.

If your adapter's name is different;
1. Copy the name of your adapter
2. Open the default.oebindings file I created 
3. Command+ F to Search for "<key>OEGenericDeviceIdentifier_519691042816_26688926777345</key>"
4. Replace all with "the name of your adapter's player one port"
5. Do the same thing for your other ports if your have a 4-port adapter.
6. Save file
7. Put this new default.oebindings file in the Bindings folder where it belongs
8. Open OpenEmu and see if it works.

This is all theory so let me know if it works or if the name of your adapter is even different than mine.  And sorry for the delayed response.


![solokeita s defaulf oebindings controller adapter](https://user-images.githubusercontent.com/18656309/29340368-e00db1ce-81db-11e7-91c2-fbfde2b39921.png)

**Comment by SoloKeita** [comment] 2017-08-15 23:31
@shax71 No worries!  I'm glad it worked for you!

**Comment by NorthWest1620** [comment] 2017-09-03 19:03
@SoloKeita I tried replacing the device identifiers in your bindings file with the one that was specific to my GC Adapter, no luck. Same behavior of only the right trigger firing and action event.

**Comment by SoloKeita** [comment] 2017-09-06 23:04
@NorthWest1620 So just to clarify, the right trigger is the only thing that works when you go to play a game?  Or the right trigger takes over when you go to set up the controls?  Because if you are using the default.oebindings file I made means you don't mess with the controls in OpenEmu, they are already set up.

**Comment by NorthWest1620** [comment] 2017-09-06 23:39
In the game I couldn't get any response from the controllers (most games require you to push start at the beginning), so there was no way to verify if the right trigger was doing anything.

Only after trying to use the controller in game did I go back to the UI to see if mappings showed up, which they didn't...and then verified that only the right trigger would register to be mapped through the UI.

**Comment by SoloKeita** [comment] 2017-09-07 00:04
@NorthWest1620 Are you playing N64 Games?  I only set this up for N64 games.

If you are playing N64 games, are you able to go into settings and map all the controls except for L&R triggers?  You may have to stop on "analog; right" so it doesn't automatically go down to the trigger.

That's what I did when I first set it up.  Then I used TextWrangler and filled in the blanks to map the L&R triggers since OpenEmu just messes it all up.

If none of that works, can you zip up your default.oebindings file and upload it for me to look at?  I want the default.oebindings file OpenEmu makes for your specific GameCube controller adapter, not the one I have uploaded.

**Comment by Cruplezone** [comment] 2018-01-21 22:20
ugh so what's the issue here why isn't it supported? i've got the 4 port one and yeah dolphin works fine on openemu only right bumper on one controller :/

**Comment by clobber** [comment] 2019-12-28 00:09
Issues using Mayflash adapters have been addressed in OpenEmu 2.2.

**Closed by clobber** 2019-12-28 00:09 UTC
Labels: Input
