### ISSUE TITLE
(10.11 El capitan beta 6) Controller issue

### ISSUE THREAD

**Issue by igarikoitz** [OpenEmu/OpenEmu#2008] opened 2015-08-04 11:22 UTC
When you're playing a game if you switch to another application and then select again OpenEmu game controls do not work in some cores. This happens with the keyboard and the Xbox 360 controller.

Info:
OpenEmu v1.0.4 (916-g1d9cca6-Release)
iMac 27" Late 2013, (3,5 GHz Intel Core i7, 24 GB 1600 MHz DDR3, NVIDIA GeForce GTX 780M 4096 MB)

**Comment by loicloic** [comment] 2015-08-31 18:09
I did not have a chance to write a full report but the summary is that I'm not able to reproduce this no DP 6 with the latest build. I'm not saying it is not happening, do you have any other software that could steal the input ? (Chrome is notorious for that)

**Comment by clobber** [comment] 2015-09-13 02:30
Closing, cannot replicate. Likely fixed?

**Closed by clobber** 2015-09-13 02:30 UTC
Labels: Input
